### ISSUE TITLE
General Chat for v1.1.0

### ISSUE THREAD

**Issue by AndrewAnnex** [AndrewAnnex/SpiceyPy#10]
Please discuss work towards v1.1.0 here or in the relevant issue.

**Comment by AndrewAnnex** [comment]
Hey all, it has been a while since I last posted here, but I have finally completed my first pass at writing docs for SpiceyPy, check them out by clicking the link in the readme. Completing the docs was a major goal of mine for a release and now that this step has been completed I am now free to work on improving how SpiceyPy is distributed, adding windows support, and possibly adding wrapper functions for those areas I had issues with last summer.

**Comment by drbitboy** [comment]
Hi,

Great package, I think I'm moving over from PySPICE.

I realize it's a design decision and it may be too late to change, but here goes (and feel free to start this as a new thread):

One question I have is, if there is an error or an empty return (e.g. sp.gdpool('INS-98301_FOV_BORESITE',0,3)) why do you return None?  Would it not be more SPICE-like to always return (n,vector,) i.e. (0,[]) in that case?  Numpy, lists, tuples and array.arrays can all have zero length.  The reasons I ask are 1) it is consistent with the SPICE documentation, and 2) that while there must always be a test of the result i.e.

    result = sp.gdpool(...)
    if result is None: ... ; continue
    n,vector = result

vs.

    n,vector = sp.gdpool(...)
    if not n: ... ; continue     ### or if n==0

vertical space is the critical screen/editor resource, IMNSHO, so I prefer the latter.

**Comment by AndrewAnnex** [comment]
You raise several good points and this is an issue I haven't really convinced myself either way on yet as there are merits to both approaches as it is a bit of a philosophical point. It isn't too late to change the approach, however the key I think will to pick one style over the other, and make changes where necessary to ensure that style is enforced for each function which will take some time to do right. Yes it would be more Spice like to return null values however that is because it is C/Fortran style which does not translate cleanly to idiomatic python, at least from what I have seen.

The returning Nones vs tuples of results is something I initially liked because it is similar in a way to an `Option` (IMHO) in Scala. Effectively a Spice function either returns a *something* or a *nothing*. If instead we always returning some value it makes the user work a bit harder to double check things, but perhaps that is necessary in either case. 

 The first example can also have the `if` statement written as `if not result: ...`

**Comment by drbitboy** [comment]
Always having to check if None was returned and never being able to use 

  n,vector = sp.routine(...)

is at least as much work as checking if n==0.

**Comment by michaelaye** [comment]
Are you guys not forgetting exeptions?

try:
    n, vector = sp.routine(...)
except:
...

I feel that Python is favoring EAFP vs LBYL (
http://www.jeffknupp.com/blog/2013/02/06/write-cleaner-python-use-exceptions/
)

About errors: If at all possible, I would strongly prefer to be told
specifically, if the SPICE machinery had an error vs a NULL result (SPICE
syntax wrong or kernels inadequate vs SPICE request returned empty).
Otherwise how would I be able to find out what went wrong?

**Comment by drbitboy** [comment]
An empty result is sometimes a desired diagnostic not an exception.

E.g. to get all of the New Horizons frame names (Frame IDs -98000 to -98999; I have done this before):

    fkNames = [s[0] for n,s in [gcpool('FRAME_-98%03d_NAME'%(i),0,1,99) for i in range(1000)] if n]

**Comment by cmillion** [comment]
My preference would be that _valid_ but empty results return an empty tuple which confirms to the format for other valid results. Invalid results should `raise` an `except`ion (even if the error is internal to SPICE). I think that a wrapper should conform as much as possible to the standards of its language and not the thing that it wraps.

**Comment by michaelaye** [comment]
I agree with @cmillion. But it possibly can be both ways (CSPICE and Python conform) as much as possible, as the exceptions can be all SpiceExceptions, designed/parsed from SPICE error messages. (I didn't research this much, so I only assume that this is possible without too much effort?)

**Comment by cmillion** [comment]
Should be. You can define custom Python exceptions that match those used by SPICE.

**Comment by michaelaye** [comment]
I know that. I meant, how much effort it is to 'fish'/parse them out of SPICE?

**Comment by cmillion** [comment]
Oh! No idea.

**Comment by michaelaye** [comment]
BTW, I will/want/absolutely want to implement this summer one of the more complex tutorials of SPICE, maybe one of the Cassini ones as a Python test case and test it against the different running Python SPICE implementations. Will also add a PR here. But first need to get a paper out...

**Comment by AndrewAnnex** [comment]
Thanks for everyone for explaining their points of view. I am pretty convinced now by your arguments @drbitboy, and thanks @michaelaye that blog post is very informative (I have read other posts by that author, just not on this topic). As I see it I should work first on reverting the areas where I attempt to return Nones. That will make things a bit more consistent to start. After that I can start looking into what to do with exceptions.

**Comment by johnnycakes79** [comment]
Any one using SpiceyPy in the IPython Notebook? For me SPICE exceptions only appear in the terminal from which the notebook was launched and not in the notebook itself. I know this is probably a problem of the notebook but anyone got any ideas on getting the exception message in the notebook?

**Comment by AndrewAnnex** [comment]
I am guessing that this is due to the way Spice returns errors, I believe by default it goes to stderr which I am guessing Ipython ignores by default. A quick google search shows that it may be possibly to capture the stderr within ipython: http://nbviewer.ipython.org/github/ipython/ipython/blob/3607712653c66d63e0d7f13f073bde8c0f209ba8/docs/examples/notebooks/Capturing%20Output.ipynb, but I have not tried this and there may be other ways to do this.

The other thing that could be done is interfacing the spice error reports with the python exceptions, but that will take some work.

**Comment by AndrewAnnex** [comment]
see #104 for progress.

**Comment by AndrewAnnex** [comment]
I just merged in #108 which has my fix for the issues with Spice errors noted here and in #104. I don't claim infallibility, so I can imagine follow up issues will start coming my way. If you haven't updated SpiceyPy for a while, please consider trying it out and letting me know how it goes. thanks!

**Comment by AndrewAnnex** [comment]
I am about to merge in #116 which adds rudimentary windows support to SpiceyPy and bumps up the version to 0.6.0. I am not sure if this will close this thread, but if it does I will either edit and reopen it for the 0.7.0 milestone or open a new thread that references this one.

**Comment by johnnycakes79** [comment]
Hi Andrew, 

I'm wondering why gfilum has not been wrapped? Is it for the same callbacks reason as some of the gf functions? 

Cheers,
Jonathan.

P.S. SpiceyPy is really gathering quite a following at the ESA's European Space Astronomy Centre here in Madrid.

**Comment by AndrewAnnex** [comment]
Hey Jonathan, thanks for writing in.

The callbacks in the gf+ section of functions was the main reason I avoided that section when I started working on spiceypy. I think wrapping the callback functions is still possible however, and now that I have made a lot of progress on completing my major goals I could start looking again at getting these functions supported. Some of these functions don't have great explanations, so I could use some help from someone who knows them well.

That all being said, I just looked at the docs for gfilum however and it doesn't look like it takes any callbacks so I might be able to get it working relatively quickly. So I will start with that and any other low hanging fruit I find. 

Glad to hear that SpiceyPy is being used at the ESA! :grinning:

**Comment by AndrewAnnex** [comment]
@johnnycakes79 check out #139 . I ended up having some time today to get to it and I got it working in no time. I ended up needing to include a rather large (180MB) MRO SPK kernel for the unit tests but it looks like the download time for that file was not prohibitively long.

**Comment by AndrewAnnex** [comment]
Hey all, so I think I am getting close to releasing 0.7.0. I think the library at a whole is very usable, so I have been figuring out how to upload to pypi. In particular the python wheels I am building with appveyor should make it much easier for users on windows to install spiceypy. 

Once 0.7.0 is released, I think that will really be the 1.0.0 release, and I will bump the version again and upload that version to the official pypi. I hope to do this by the end of the month. 

Once 1.0.0 is cut, versions will increment the last digit as more spice functions are supported. If a new cspice release occurs the first digit will be incremented. The middle digit will be incremented if bugs are discovered and fixed (not adding a new feature, unless 'working' is a feature).

**Comment by michaelaye** [comment]
Congrats on reaching 1.0.0! Just a comment on your versioning approach though: That would be highly unusual compared to the usually applied [semantic versioning model](http://semver.org).
Do you have a special reason for not following this simple separation model (quote from above linked website):


> Given a version number MAJOR.MINOR.PATCH, increment the:
> * MAJOR version when you make incompatible API changes,
> * MINOR version when you add functionality in a backwards-compatible manner, and
> * PATCH version when you make backwards-compatible bug fixes.
>  
> Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.

I think, new SPICE toolkit version number might justify an increase in the major version number, as it's safer to state that the current version is incompatible with previous toolkits and things 'might' break (although they usually don't between toolkits), so this is a matter of taste maybe. But your added funcionality is a prime case for increasing the MINOR number, and so is are the patches for increasing PATCH?

**Comment by AndrewAnnex** [comment]
Nothing is set in stone as 1.0.0 isn't even out yet, but the main reason for what I said was that I felt that it makes sense for my workflow. Considering I haven't been following semantic versioning for this project yet, I don't feel particularly beholden to it. Any structure at this point is better than the more or less erratic version bumps I have made, even if it isn't exactly to spec with semantic versioning. I don't anticipate making patches... ever.. but I guess I might as well follow semantic versioning just in case.

**Comment by michaelaye** [comment]
But you write about bugfixes above? Why do you write about them if you never want to do them? that's what the patches are for? Unless i'm missing something...

**Comment by AndrewAnnex** [comment]
**No, that is not what I am not saying at all!** Bug fixes are fine, I just don't think I will be patching older versions of the library, as I don't see how it would ever be necessary. Patches are for when you cut a release of something (say 1.0.0) and development continues (say we have just released 1.1.0) but a user has an issue on the older (1.0.0) version and is unable to upgrade. Then you would checkout the older minor version and issue a patch (ie 1.0.1) with a bugfix. I am assuming here that the issue does not occur in a newer version (say 1.1.0 or newer) and that something else is preventing the user from upgrading to 1.1.0 or newer. Unless I am mistaken in what a patch is, what I am claiming is that this is a highly unlikely scenario for the users of spiceypy, largely because I don't know why upgrading would not be an option. And again as I said, using semantic versioning resolves the issue as I would then be able to issue a patch, no matter how unlikely it is.

**Comment by AndrewAnnex** [comment]
SpiceyPy version 1.0.0 has been released! You should all be able to `pip install spiceypy` now.

**Comment by michaelaye** [comment]
A patch is released whenever you are fixing a bug or incorrect behavior, with that fix being backward compatible. It has nothing to do with the difference between newer versions. In your example, when you have released 1.0.0, and you have NOT released 1.1.0, and you have to fix something you still would release 1.0.1. You might confuse it with `backporting`, which happens when a new feature is introduced into older versions in a backwards compatible way? Patching really just means fixing anything that is wrong,buggy, incorrect behavior. No other meanings are implied.

**Comment by michaelaye** [comment]
Congrats on the 1.0.0 release, btw!

**Comment by AndrewAnnex** [comment]
to make my life easier (that is, using something well defined by someone else), I switched over to _true_ semantic versioning when I merged in a commit today that changed the master branch's version to 1.1.0.dev (though no api changes occured, just stuff in tests/setup.py/etc for conda builds).

**Comment by jjjefferson** [comment]
This may be a bit of an odd question/situation, but some insight may be helpful. I have installed SpiceyPy for use with another python package, but I run into an error where that package calls upon the module SpiceyPy.wrapper . Unfortunately I have not been able to find any documentation on this module past spiceypy v0.6.2. Has this module been removed/replaced? Or am i just missing something? Thanks for the help!

**Comment by drbitboy** [comment]
import SpiceyPy

is now

import spiceypy

?

**Comment by jjjefferson** [comment]
Thanks for responding, although I am already using import spiceypy not import SpiceyPy ...... its telling me there is no module named spiceypy.wrapper . Although I have found documentation that says there is  in previous versions, but I haven't found anything from recent versions. I have tried v1.1 and v.7. So i am wondering if this module may have been replaced/renamed? The call on that module is in the setup.py file of the other package so I realize that I may have to do some tweaking.

**Comment by michaelaye** [comment]
I remember i had similar problems when the change to `import spiceypy` happened. I had to completely remove the package and reinstall it to make it work. With pip, that action is just a `pip uninstall spiceypy` away, fortunately.

**Comment by AndrewAnnex** [comment]
the rename of the wrapper file happened relatively recently in the git history, it was renamed to spiceypy.py . The import is now just `import spiceypy` . Upgrading to the new version should be fairly painless, the 1.0.0 release can be installed (or uninstalled) via pip: `pip install spiceypy` 

let me know if you are still having issues @jjjefferson

**Comment by jjjefferson** [comment]
Ok awesome! It worked thank you all so much!

**Comment by AndrewAnnex** [comment]
Version 1.1.0 has just been released. Given that this thread is a few years old, and that I have since added the gitter room I will soon be closing this issue.
