### ISSUE TITLE
Missing non-wrapper (=Fortran??) routine

### ISSUE THREAD

**Issue by michaelaye** [AndrewAnnex/SpiceyPy#111]
The docs for `inrypl` 
http://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/inrypl_c.html
have a nice example for calculating intercept of instrument boresight with the Saturn ring plane, but it uses a weird, non-wrapper (hence, no `_c` at the end) function called `stlabx_` :

```bash
We now wish to find the vector corvec that, when corrected for
             stellar aberration, yields borvec.  A good first approximation is
             obtained by applying the stellar aberration correction for
             transmission to borvec.  Note that the routine called is not
             a wrapper, so there is no letter 'c' at the end of its name.
             The prototype for this routine is declared in SpiceZfc.h.
             ./
             stlabx_ ( (doublereal *) borvec, scssb+3, corvec );
```
and it's not currently in SpiceyPy. Could this be implemented as well?

**Comment by AndrewAnnex** [comment]
I looked at the source code for `stlabx`and it looks like it really is just a call to `vminus` and `stelab`. In fact I pasted the entirety of the code here:
```
  230 C     Obtain the negative of the observer's velocity.  This 
  231 C     velocity, combined with the target's position, will yield
  232 C     the inverse of the usual stellar aberration correction,
  233 C     which is exactly what we seek.
  234 C
  235       CALL vminus( vobs, negvel )
  236 
  237       CALL stelab( pobj, negvel, corpos )
  238 
  239       CALL chkout( 'STLABX' )
  240       RETURN
``` 
So that should get you what you need for now, but it also shouldn't be a problem at all to implement the function in the wrapper.

**Comment by michaelaye** [comment]
Do you have a place where this extra or missing functions should go? If you point me to it, I could give it a shot.

**Comment by michaelaye** [comment]
But, as you said, if it's just vminus and stelab as above, maybe not even worth the effort?

**Comment by AndrewAnnex** [comment]
we can add it, we should probably make an "extras.py" file for it as there may be more helper functions like this that are sufficiently simple to write in python. feel free to take this on or I can probably get to it in the next few days.

**Comment by AndrewAnnex** [comment]
I am closing this issue for now, I can open a new issue to add a place in the repo for these sort of helper functions
