### ISSUE TITLE
general py.test call fails

### ISSUE THREAD

**Issue by michaelaye** [AndrewAnnex/SpiceyPy#113]
I don't know if this is supported, but I don't see any comment in the README.md otherwise:
I just called `py.test` inside the SpiceyPy to see if this works, and it ends up with
```bash
===================== 125 failed, 421 passed in 78.51 seconds =====================
```
From a little browsing, I can see that most failures have this error signature:
```bash
E           SpiceyPy.support_types.SpiceyError:
E           ================================================================================
E
E           Toolkit version: N0065
E
E           SPICE(NOSUCHFILE) --
E
E           The attempt to load "/Users/klay6683/Dropbox/src/SpiceyPy/test/testKernels.txt" by the routine FURNSH failed. It could not be located.
E
E           furnsh_c --> FURNSH --> ZZLDKER
E
E           ================================================================================
```
I will try to get into this over the weekend and maybe start a pull request for discussion how to fix this (if this is indeed an issue and not unsupported, maybe your current way of testing works differently, but then it should be added to the docs)

**Comment by AndrewAnnex** [comment]
no, that *should* work (py.test I have found is a little finicky), but this could be an issue with your system, for example if you have SpiceyPy still install it may be actually importing the library from your site-packages not the new code in your wrapper. When I develop I typically uninstall the package from python. Although the error could be real, did you run the gettestkernels script? The best/ easiest thing to do is to simply make the changes and the make a PR against the repo, TravisCI will run the tests for you.

**Comment by michaelaye** [comment]
FYI, I have the exact same errors in OSX 2.7, 3.4 and under Linux, so most lilkely not my specific setup. (But all my setups use miniconda as dist manager?) 
The uninstallation of the package is the exact opposite of the py.test recommendation (see [here](https://pytest.org/latest/goodpractises.html)). 
I also remember having finicky probs with py.test but can't remember the details yet. Working it.

**Comment by michaelaye** [comment]
So, I see that `gettestkernels.py` is supposed to create the file `testKernels.txt` but no module is importing `gettestkernels` to get the kernels, so I don't understand how it is supposed to work?

**Comment by michaelaye** [comment]
So it seems you did not meant to execute the test by simply running 'py.test' inside the package directory, but by executing 'python setup.py test'. But then I get this:
```bash
$ python setup.py test
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    import test.gettestkernels as getTestKernels
ImportError: No module named 'test.gettestkernels'
```
Which makes sense because `test` is nothing that is known to the system. I believe that an extra test class in setup.py is currently being frowned upon. Do you mind if I rearrange things to make it work? I don't think it's a requirement for Travis to have this PyTest class in setup.py or is it?

**Comment by AndrewAnnex** [comment]
the "test" in "python setup.py test" is defined in setup.py which is a standard practice see good practises for pytest: https://pytest.org/latest/goodpractises.html. I think that a compromise can be achieved by having a startup check in the test script that looks for the test kernels (and calls out to the gettestkernels script to grab them if absent)   

My view is go ahead and make whatever changes you want/need to make and we can sort out any issues I would have with it during review. As long as Travis CI (and coveralls) is happy then I will most likely also be happy.

**Comment by AndrewAnnex** [comment]
I merged in a fix that should resolve this issue for now, the tests if run by py.test will now do a naive check for the existence of the kernels and attempt to download them if absent. I have seen this work on windows (via appveyor) and it should also work for mac and linux environments. Simply run `py.test test` to run the tests.

**Comment by michaelaye** [comment]
Confirmed that this is fixed on Linux and OSX. But wasn't it version 0.6.0 already before? Thanks!

**Comment by AndrewAnnex** [comment]
nope, 0.5.3.
