### ISSUE TITLE
don't force user to provide length of output string

### ISSUE THREAD

**Issue by michaelaye** [AndrewAnnex/SpiceyPy#115]
This comes from C of course but is very un-pythonic.
See for example for getfov:

http://naif.jpl.nasa.gov/pub/naif/toolkit_docs/C/cspice/getfov_c.html

the required inputs are 4:

```
   VARIABLE  I/O  DESCRIPTION 
   --------  ---  -------------------------------------------------- 
   instid     I   NAIF ID of an instrument.
   room       I   Maximum number of vectors that can be returned. 
   shapelen   I   Space available in the string `shape'.
   framelen   I   Space available in the string `frame'.
   shape      O   Instrument FOV shape. 
   frame      O   Name of the frame in which FOV vectors are defined. 
   bsight     O   Boresight vector. 
   n          O   Number of boundary vectors returned. 
   bounds     O   FOV boundary vectors. 
 ```
but shapelen and framelen are just the lengths for the strings of shape and frame in the output. This is usually not required in Python and it would be nice if the user, especially the not-C versatile user who does not understand what is going on, would not need to provide this number. 
How about setting it to something large like `100` that SpiceyPy sets internally whereever such length of a string is required?
What do people think? I think, but am not sure now, that we did that at PySPICE?

**Comment by AndrewAnnex** [comment]
So I think I will actually find time soon to tackle this, what I think makes sense is to keep the parameters but define a large enough default value so that users can optionally override that default.

**Comment by michaelaye** [comment]
I'm not sure the user ever needs or should need to set that default? In Python I don't need to know the length of a returning string, to require that knowledge is very un-pythonic and is a pure remnant from C/FORTRAN. If it's easier to /hide/ it for you by setting defaults, I can understand that as a reason, but I don't see why to keep it. Our pyspice implementation got rid of it completely, IIRC.

**Comment by AndrewAnnex** [comment]
yeah I will look into this, I wanted to keep those available adjustable in case whatever magic number I decided on was too much or too little.
