### ISSUE TITLE
change to lower case import broken

### ISSUE THREAD

**Issue by michaelaye** [AndrewAnnex/SpiceyPy#127]
Since the change to lowercase, SpiceyPy does not work here anymore. If I install the git-hash before that change, things work fine.
Here's the errors I get, but in words: IPython still only finds `SpiceyPy`, not `spiceypy`, but it doesn't find everything, so I guess you changed it at enough places to break it, but not enough to make it work?
I guess it works at your place because you never tried a fresh install?
```python
In [1]: import SpiceyPy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-756a48dc04ba> in <module>()
----> 1 import SpiceyPy

/Users/klay6683/miniconda3/lib/python3.4/site-packages/spiceypy-0.6.1-py3.4.egg/SpiceyPy/__init__.py in <module>()
      3 __all__ = ['wrapper']
      4
----> 5 from spiceypy.wrapper import *
      6
      7 #Default setting for error reporting so that programs don't just exit out!

ImportError: No module named 'spiceypy'
> /Users/klay6683/miniconda3/lib/python3.4/site-packages/spiceypy-0.6.1-py3.4.egg/SpiceyPy/__init__.py(5)<module>()
      4
----> 5 from spiceypy.wrapper import *
      6

ipdb> exit

In [2]: import spiceypy
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-c5b546b9c11f> in <module>()
----> 1 import spiceypy

ImportError: No module named 'spiceypy'
> <ipython-input-2-c5b546b9c11f>(1)<module>()
----> 1 import spiceypy

ipdb>
```

**Comment by AndrewAnnex** [comment]
Did you uninstall the older version first? Make sure you go through and remove any old installs or old cloned repositories.

Also no, I have CI in place with Travis and Appveyor which spin up fresh (new) instances for each new commit, and I don't (aka: haven't for a long time) merged in commits that have failing builds.

**Comment by michaelaye** [comment]
I did remove the older install with `pip uninstall`, which did not help.
Only a removal of the build folder solved this, even so I tried 'python setup.py clean' before. I did not realize that only a `python setup.py clean --all` really removes everything from the build section. Sorry for the noise.
