### ISSUE TITLE
Remove un-pythonic 'found' response from results

### ISSUE THREAD

**Issue by michaelaye** [AndrewAnnex/SpiceyPy#128]
Functions like `bodn2c` return a tuple of `(result, True)` which is very un-pythonic, as if the execution did not work as expected, it should throw a catch-able exception, in my opinion.
To not have this supported means to constantly unpack the resulting tuple into something one uses and something to be thrown away, which makes for cumbersome, less readable code.
In my opinion, it would be good if that could be changed to only return the result, and if it would return False, to throw specific exceptions what went wrong.
If you give me a pointer where to attack this, I could help. I think we had this the way I suggest in our `pyspice` implementation, and found it very pleasant to work with, so I could look up how Roberto coded that.

**Comment by AndrewAnnex** [comment]
Ok so I have been off doing other things for a bit and I am looking to start working again on this project. I will look into what to do about this over the next few days, but the first concern I have is that doing this would possibly make users wrap calls to the wrappers with trys which doesn't sound fun to me. While returning a status code might be annoying, it gives a lightweight way to determine if a function call was successful. I kind of feel that exceptions should be reserved for when something terrible happens (like a segfault) and exceptions are not appropriate for cases when getting "nothing" out is a valid result. The example you gave for `bodn2c` I think illustrates this, as the user can ask for something that is not loaded into Spice. This would not be an exception, as it is user error. I would rather leave it up to the user to properly check the output for now. Earlier, I had a pattern that returned either a tuple of all the function return or a `None`. Coming from Scala land this was idiomatic to that language (perhaps not python) but I got some pushback here on that. In short I will think about this over the next few days, post anything supporting your side and I will check it out before making a decision

**Comment by michaelaye** [comment]
It seems like you underestimate the role of exceptions in Python. They are a very normal idiom in Python, and are even used for flow control, including the Python programmers themselves. For example, the end of EVERY container loop is indicated by a StopIteration exception which is then caught by the looping code (internally) to end the loop. A segfault however is a C-based problem so serious that it even cannot be caught by exceptions, so your expectation is kinda off there. Exceptions are very much thought to be used for user errors and prevent hidden bugs by the user forgetting to check old language style things like return codes. Imagine the result is being used only much further down the line, it would be much harder to find where the problem was created. In the case of `bod2nc` there is no other reasonable result as to get the result of the conversion. If for some reason that conversion fails, a very important SPICE rule, which is to have the required kernels loaded at this point, was not followed. As a SPICE user I think I would want to know immediately that I forgot to have kernels loaded at this point.

**Comment by AndrewAnnex** [comment]
@michaelaye I have pushed a pr that attempts to handle your feedback. Note that the wrapper functions themselves have not changed as I handle the check inside a decorator, but the usage would be as one would expect (see changes to unit tests). It is still a work at progress at this point though, so more changes are likely.

**Comment by AndrewAnnex** [comment]
I merged in the PR so I am calling this done

**Comment by michaelaye** [comment]
:+1: will gives this a test soon.
