### ISSUE TITLE
Install to Anaconda

### ISSUE THREAD

**Issue by voldyy** [AndrewAnnex/SpiceyPy#133]
Hi Andrew,

Is there a way to install SpiceyPy to the instance of Anaconda's Python on a Linux server instead of the default Python? I assume it involves some method of doing a manual installation where you can specify the Python path.

Thanks,
Mihir Patel

**Comment by AndrewAnnex** [comment]
Hello Mihir,
I don't use anaconda personally, but I am pretty sure it is possible. I searched for a little bit and found the two following links that should help you out:

- https://stackoverflow.com/questions/22312665/install-python-packages-to-correct-anaconda-environment
- https://github.com/ContinuumIO/anaconda-issues/issues/358

I do eventually want to get spiceypy in the conda system, but that will probably take me a while to get to as I have some other changes I want to make before.

Hope that helps.

**Comment by voldyy** [comment]
Hi Andrew,
The first link you provided gave me the solution. Thank you!
