### ISSUE TITLE
utils folder not being copied during setup.py install

### ISSUE THREAD

**Issue by msbentley** [AndrewAnnex/SpiceyPy#136]
I've just tried to install the latest SpiceyPy and it looks like the spiceypy/utils directory is not being copied during setup.py install, and hence imports fail on the line:

```from .utils import support_types as stypes```

If I copy the folder manually, all works as expected. This is on linux x64.

**Comment by AndrewAnnex** [comment]
Thanks for letting me know about this. I also noticed last night that my documentation builds are broken and the issue I saw is probably related to this. I hope to get a fix out in the next day or so.

-Andrew Annex

**Comment by AndrewAnnex** [comment]
ok it looks like I got this all fixed, I have a pr building on my various ci services and I should be able to merge it later tonight.

**Comment by msbentley** [comment]
Works fine for me - many thanks!
