### ISSUE TITLE
spkez including geodetic correction

### ISSUE THREAD

**Issue by migueldvb** [AndrewAnnex/SpiceyPy#169]
I am looking for the state (position and velocity) of a minor body relative to an observatory on Earth corrected for light time aberration. The results I get with `spiceypy.spkez` are consistent with JPL Horizons except for the velocity of the object with respect to the observer that is off by 0.1 km/s. This is difference is likely due to having introduced an observatory defined by longitude, latitude and altitude in Horizons while spkez takes the NAIF ID 399 coresponding to Earth. Is there any way to obtain the state of a body relative to a position given in latitudinal coordinates?

**Comment by AndrewAnnex** [comment]
hey @migueldvb I am sure there is a way to do this but I am not able to fully investigate this until the weekend at the earliest. If this is time sensitive I would suggest sending an email to the naif to get a full answer. But if I had to guess I think `spkpvn` could help or if you are really interested in the raw values in the kernel pool maybe `bodvar` with `bodc2s` may help, as you would probably want to get out the lat/lon/alt for the observer. IIRC one of the spice tutorials does this with a earth based telescope but I can't remember which one it is. Hope that helps.

**Comment by migueldvb** [comment]
I have sent this question to the naif_discuss mailing list but it looks like it got stuck in their filters...

**Comment by AndrewAnnex** [comment]
just to check, you did subscribe before sending that email right? You can also email the naif dev team directly.

**Comment by AndrewAnnex** [comment]
I am closing this issue for now, as there has been little activity here and github isn't really the best place for these sorts of questions
