### ISSUE TITLE
update wheel/appveyor builds to include python 3.6

### ISSUE THREAD

**Issue by AndrewAnnex** [AndrewAnnex/SpiceyPy#184]
we should start transitioning builds to include and build artifacts for python 3.6, now that it is available in appveyor this shouldn't be too difficult for windows.

**Comment by michaelaye** [comment]
Is the lack of wheel builds the reason sciceypy currently doesn't install via pip under OSX as well?

```bash
Collecting spicepy (from -r pip_packages_to_install.txt (line 7))
  Could not find a version that satisfies the requirement spicepy (from -r pip_packages_to_install.txt (line 7)) (from versions: )
No matching distribution found for spicepy (from -r pip_packages_to_install.txt (line 7))
```

**Comment by AndrewAnnex** [comment]
you misspelled spiceypy, so no ;)

**Comment by michaelaye** [comment]
Thanks for catching that! Not sure how long that was already lurking in my env install scripts.. Guess I didn't do SPICE for a while! ;)

**Comment by AndrewAnnex** [comment]
I am closing this ticket as wheels/ conda packages for windows on python 3.6 have been published. I would have also posted macOS wheels/conda packages but there is a bug in the travisCI yaml parser that I am seeing other people struggling with at the moment.
