### ISSUE TITLE
Probably unrelated to SpiceyPy itself: `no module named "six"`

### ISSUE THREAD

**Issue by ChristopherRabotin** [AndrewAnnex/SpiceyPy#185]
I am using SpiceyPy in order to do frame transformations and use de430 for planetary ephemerids. I can install and use SpiceyPy correctly on my local machine, but I am having issues installing this on my travis-ci testing virtual machines, cf. https://travis-ci.org/ChristopherRabotin/smd/builds/207118128 . I don't think this issue is specifically related to SpiceyPy, but I was wondering whether you had encountered that error before, or whether you had any tips on fixing this?
Thanks.

**Comment by AndrewAnnex** [comment]
ok that is really weird, that error would be indicating that the `six` package is not installed but I can see that the travis worker is installing it in the log line above installing spiceypy. Maybe try adding the step to install six/ other python deps via the requirements file to your travis yaml? I may have ran into this before but idk. I do this in my yaml in the `before_install` stage.

**Comment by ChristopherRabotin** [comment]
Thanks. I added `six` as an independent import before the `pip`-ing of the requirements, and the build no longer fails on that.

**Comment by AndrewAnnex** [comment]
cool, happy to help.
