### ISSUE TITLE
Install spice on windows from source

### ISSUE THREAD

**Issue by ramsinghdayal** [AndrewAnnex/SpiceyPy#194]
> %run C:\Users\Ramdayal\SpiceyPy\setup.py install

Host OS: Windows
Attempting to move: C:\Users\Ramdayal\SpiceyPy\cspice\src\cspice\cspice.dll   to: C:\Users\Ramdayal\SpiceyPy\spiceypy\utils\cspice.dll
An exception has occurred, use %tb to see the full traceback.

SystemExit: cspice.dll file not found, what happend?: [Error 2] The system cannot find the file specified

Problem: cspice.dll file is missing? How can I get cspice.dll?

Thank you.

**Comment by AndrewAnnex** [comment]
hello, thanks for writing in.
it sounds like you are trying to install spiceypy from the source code on windows, please use the `pip install spiceypy` command or the anaconda distribution instead to install spiceypy.

 While it is possible to install spiceypy from source on windows, it is very difficult and time consuming to properly configure a system.

please also respond with more specifics like the version of windows you are using, python version, and if the system is 64bit or not.

hope that helps

**Comment by ramsinghdayal** [comment]
>  %run C:\Users\Ramdayal\SpiceyPy\setup.py install

Unable to find CSPICE at C:\Users\Ramdayal\SpiceyPy\cspice. Attempting to Download CSPICE For you:
Gathering information...
('SYSTEM:   ', 'Windows')
('PROCESSOR:', 'Intel64 Family 6 Model 58 Stepping 9, GenuineIntel')
('MACHINE:  ', '64bit')
('Best option:', 'PC_Windows_VisualC_64bit')
('URL: ', 'https://naif.jpl.nasa.gov/pub/naif/misc/toolkit_N0066/C/PC_Windows_VisualC_64bit/packages/cspice.zip')

Downloading...
Attempting to download spice...
Unpacking... (this may take some time!)
Host OS: Windows
Attempting to move: C:\Users\Ramdayal\SpiceyPy\cspice\src\cspice\cspice.dll   to: C:\Users\Ramdayal\SpiceyPy\spiceypy\utils\cspice.dll
An exception has occurred, use %tb to see the full traceback.

SystemExit: cspice.dll file not found, what happend?: [Error 2] The system cannot find the file specified

> sys.version
'2.7.10 | 64-bit | (default, Oct 21 2015, 17:08:47) [MSC v.1500 64 bit (AMD64)]'

**Comment by AndrewAnnex** [comment]
you really should not because I provided anaconda and python wheels prebuilt for windows because it requires a large (last time I tried, multi gigabyte) visual studio installation along with the command line tools that must be in your path. Advanced users would be understand this and would not require instructions from me to setup their system to build from source.  

In any case, since you installed spiceypy from the wheels I provide you should be ready to use spiceypy. 

Why do you want to install from source?

**Comment by AndrewAnnex** [comment]
closed as issue was resolved
