### ISSUE TITLE
CSPICE not downloading for certain connections

### ISSUE THREAD

**Issue by marcsit** [AndrewAnnex/SpiceyPy#196]
Andrew, 

both using the wifi connection at Flagstaff and from ESAC I was getting the following error:

_Download failed with URLError: [SSL: SSLV3_ALERT_HANDSHAKE_FAILURE] sslv3 alert handshake failure (_ssl.c:645), trying again after 15 seconds!_

I was trying to do it with pip. I solved the issue by cloning SpiceyPy and then downloading cspice and unzipping it in the main directory and installing it with setup.py

Might be a glitch of for networks with a certain firewall for urllib?

Cheers!

**Comment by AndrewAnnex** [comment]
this is an issue other users have had (see #188) and it basically means that the version of ssl your python is using is too old to understand the newer JPL TLS 1.2 certificate for the https connection. This actually was a common issue among other open source projects over the past few months so by now if you google `python TLS 1.2` a lot of stuff should pop up. This is particularly problematic on Macs.

This link has a decent explaination of the issue, but without a fix: https://pyfound.blogspot.com/2017/01/time-to-upgrade-your-python-tls-v12.html

So there isn't really anything to fix with urllib, but I wish I could find an exact solution for people to update their systems. In any case downloading cspice manually is the way around this if upgrading ssl/openssl is not an option.  

Thanks for writing in, closing the issue
