### ISSUE TITLE
Make SpiceyPy 2.1.0 release

### ISSUE THREAD

**Issue by AndrewAnnex** [AndrewAnnex/SpiceyPy#205]
only 5 more DSK functions left to wrap, maybe make that and adding ckw05 as the target and cut a new release. target end of October?

**Comment by jdiazdelrio** [comment]
I did not manage to work on the setup file, but in a couple day I should have more time. Sounds good.

**Comment by AndrewAnnex** [comment]
I decided that a minor version bump is now required given the number of additional functions now wrapped and other changes. I am also pushing the release to mid November to give current PRs a bit more time
