### ISSUE TITLE
Add explainer to docs about installation issues

### ISSUE THREAD

**Issue by AndrewAnnex** [AndrewAnnex/SpiceyPy#233]
although #202 improved installation success with bare python installs, it does not totally solve the runtime dependency issue because setuptools falls back onto easy_install for the setup_requires and install_requires dependencies. This means that installations may still fail as easy_installs are a bit brittle for some transitive dependencies and ultimately inefficient for things like numpy as it does not take advantage of wheels either. Ultimately try to patch all of the contingencies will take too much effort, so it would just be better to tell users to install wheel, numpy, and urllib3[secure] in that order before trying to install on a clean python.  

see:
https://github.com/pypa/setuptools/issues/917
https://pip.readthedocs.io/en/1.4.1/cookbook.html#controlling-setup-requires
https://www.python.org/dev/peps/pep-0518/

**Comment by jdiazdelrio** [comment]
An alternative is to work-around those issues by creating a pip-based solution within the run method of the InstallSpiceyPy, with a **try-except** block where before the try we use pip install for the dependencies and the within the except, we remove anything that has been installed by pip install, should the installation fails.

**Comment by AndrewAnnex** [comment]
see https://github.com/pypa/pip/issues/1820.
I am a bit skeptical about that as a workaround for the moment, as there are several ongoing PRs in setuptools that appear related and so this can be called a known deficiency in setuptools, and comments that say that calling pip like that can cause issues. I would rather wait until setuptools is updated and or pep518 is fully baked in to pip.
