### ISSUE TITLE
no cspice.dll after successful pip install

### ISSUE THREAD

**Issue by CAReeser** [AndrewAnnex/SpiceyPy#242]
installed on 64 Windows 10 using pip install spiceypy. It appears all goes well, except there is no cspice.dll anywhere to be found and import into VSC or python fails with module not found (see below).

C:\Python27\Lib\site-packages\spiceypy>pip install spiceypy
Collecting spiceypy
  Downloading spiceypy-2.1.0.tar.gz (113kB)
    100% |################################| 122kB 423kB/s
Requirement already satisfied: numpy>=1.12.0 in c:\python27\lib\site-packages (from spiceypy)
Requirement already satisfied: six>=1.9.0 in c:\python27\lib\site-packages (from spiceypy)
Requirement already satisfied: certifi>=2017.1.23 in c:\python27\lib\site-packages (from spiceypy)
Building wheels for collected packages: spiceypy
  Running setup.py bdist_wheel for spiceypy ... done
  Stored in directory: C:\Users\crees\AppData\Local\pip\Cache\wheels\b6\77\3a\7cf4930d4ee32df5e32a8cd6bd31ecb6b66f40769cf4b895b5
Successfully built spiceypy
Installing collected packages: spiceypy
Successfully installed spiceypy-2.1.0

C:\Python27\Lib\site-packages\spiceypy>cd\
C:\>cd python27

C:\Python27>python
Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import spiceypy as spice
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\spiceypy\__init__.py", line 25, in <module>
    from .spiceypy import *
  File "C:\Python27\lib\site-packages\spiceypy\spiceypy.py", line 27, in <module>
    from .utils.libspicehelper import libspice
  File "C:\Python27\lib\site-packages\spiceypy\utils\libspicehelper.py", line 34, in <module>
    libspice = CDLL(sitePath)
  File "C:\Python27\lib\ctypes\__init__.py", line 366, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126] The specified module could not be found
>>>

**Comment by AndrewAnnex** [comment]
hey @CAReeser this is a known issue of a strange interaction between setuptools, wheel, and pip where the bit of code that generates the dll is skipped during bdist_wheel. The current fix is to install without wheel using the no cache dir option during pip install. see #240

**Comment by CAReeser** [comment]
That did it, thanks for the rapid response. Sorry, I did not see #240.
