### ISSUE TITLE
Encountering AttributeError running Cassini example

### ISSUE THREAD

**Issue by OrbitalMechanic** [AndrewAnnex/SpiceyPy#244]
I'm attempting to run SpiceyPy 2.1.0 on a Mac Pro (late 2013) running Mac OS X ver. 10.12.6 under Python 2.7.13. The documentation gives an example running SpiceyPy beginning on page 9 called the Cassini Position Example. The code has been attached to this note named cassini-2.py.txt. In running this example I noticed the following.

1. The command spice.tkvrsn("TOOLKIT") does not output the toolkit version as cited in the documentation
2. All remaining messages output to standard output are identical to what is shown in the example in the documentation.
3. Lastly, an AttributeError is encountered with the message:
Traceback (most recent call last):
  File "/Users/user/Desktop/Cassini_Example/cassini-2.py", line 86, in <module>
    ax.plot(positions.T[0], positions.T[1], positions.T[2])
AttributeError: 'list' object has no attribute 'T'

From what I can tell, positions is a list 4000 elements long, where each element is a Cartesian position vector for each interstitial point in time and that 
ax.plot(positions.T[0], positions.T[1], positions.T[2])
is attempting to reshuffle positions so that X, Y and Z components form the first, second and third arguments respectively.

The questions I have are:

1. Am I interpreting things correctly?
2. How do I correct the error?

Please advise.

[cassini-2.py.txt](https://github.com/AndrewAnnex/SpiceyPy/files/1565449/cassini-2.py.txt)

**Comment by OrbitalMechanic** [comment]
I believe I found a workaround for the ArrtibuteError. I took the positions list and used numpy.vstack function to stack the arrays vertically and stored the stacked arrays in a new variable xyz_pos. Then in function plot, sliced xyz_pos for the Xx, Y and Z components to be plotted (see attached file).

Hope this helps.

[cassini-3.py.txt](https://github.com/AndrewAnnex/SpiceyPy/files/1565555/cassini-3.py.txt)

**Comment by OrbitalMechanic** [comment]
I believe I found a workaround for the ArrtibuteError. I took the positions list and used numpy.vstack function to stack the arrays vertically and stored the stacked arrays in a new variable xyz_pos. Then in function plot, sliced xyz_pos for the Xx, Y and Z components to be plotted (see attached file).

Hope this helps.

[cassini-3.py.txt](https://github.com/AndrewAnnex/SpiceyPy/files/1565558/cassini-3.py.txt)

**Comment by AndrewAnnex** [comment]
@OrbitalMechanic what toolkit version is being output? If it is not N66 then something is wrong.

second, it sounds like I neglected to update the cassini example in the documents for the new version. Currently it looks like it is returning a list of tuples which I think used to return a numpy array. Using Vstack is a more than reasonable solution and I could just update the example to include it, but I am still curious about the version mismatch.

**Comment by OrbitalMechanic** [comment]
Andrew,

Thanks for getting back to me. The CSPICE version I get is N0066, so I have the correct version of CSPICE installed.

f you wish to  use my workaround in the SpiceyPy documentation, please be all means feel free to use it.

Lastly, from taking a closer look at the Cassini example, it seems to me that the example was run in Jupyter, is that correct?

Once again, thanks for getting back to me.

Sam Dupree.

**Comment by AndrewAnnex** [comment]
Yes, it was run in a jupyter notebook, hence the missing print calls.
