### ISSUE TITLE
 States of  Ephemeris bodies

### ISSUE THREAD

**Issue by ramsinghdayal** [AndrewAnnex/SpiceyPy#247]
I am having following kernal files 
Following kernels for calculating the Doppler shift at IDSN:
idsn32.bsp
idsn32.tf
naif0012.tls
pck00010.tpc
earth_070425_370426_predict.bpc
earth_topo_050714.tf
de430.bsp
vco_20170101000000_20170328040000.bsp

How can I derive states of  Ephemeris bodies? Thank you.

**Comment by AndrewAnnex** [comment]
I suggest you read the materials made available by the naif at https://naif.jpl.nasa.gov/naif/ and use the contact info their to ask these kinds of questions. I don't consider these sorts of questions a bug  or issue so I am closing it.
