### ISSUE TITLE
Spiceypy fails build on Raspian. File in wrong format error.

### ISSUE THREAD

**Issue by CAReeser** [AndrewAnnex/SpiceyPy#249]
Builds OK on Win10. Fails on Raspian. Could be a build environment issue, but I do not have the experience to determine. Can someone translate the error for me? Thanks, Cliff

pi@orerry200:~ $ sudo pip install spiceypy
Collecting spiceypy
  Using cached spiceypy-2.1.0.tar.gz
Requirement already satisfied: certifi>=2017.1.23 in /usr/local/lib/python2.7/dist-packages (from spiceypy)
Requirement already satisfied: numpy>=1.12.0 in /usr/local/lib/python2.7/dist-packages (from spiceypy)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from spiceypy)
Building wheels for collected packages: spiceypy
  Running setup.py bdist_wheel for spiceypy ... error
  Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lLmgYg/spiceypy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpOKQaxbpip-wheel- --python-tag cp27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-2.7
  creating build/lib.linux-armv7l-2.7/spiceypy
  copying spiceypy/spiceypy.py -> build/lib.linux-armv7l-2.7/spiceypy
  copying spiceypy/config.py -> build/lib.linux-armv7l-2.7/spiceypy
  copying spiceypy/__init__.py -> build/lib.linux-armv7l-2.7/spiceypy
  creating build/lib.linux-armv7l-2.7/spiceypy/utils
  copying spiceypy/utils/callbacks.py -> build/lib.linux-armv7l-2.7/spiceypy/utils
  copying spiceypy/utils/support_types.py -> build/lib.linux-armv7l-2.7/spiceypy/utils
  copying spiceypy/utils/libspicehelper.py -> build/lib.linux-armv7l-2.7/spiceypy/utils
  copying spiceypy/utils/__init__.py -> build/lib.linux-armv7l-2.7/spiceypy/utils
  running egg_info
  writing requirements to spiceypy.egg-info/requires.txt
  writing spiceypy.egg-info/PKG-INFO
  writing top-level names to spiceypy.egg-info/top_level.txt
  writing dependency_links to spiceypy.egg-info/dependency_links.txt
  reading manifest file 'spiceypy.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'spiceypy.egg-info/SOURCES.txt'
  installing to build/bdist.linux-armv7l/wheel
  running install
  ('Checking the path', '/tmp/pip-build-lLmgYg/spiceypy/cspice')
  Unable to find CSPICE at /tmp/pip-build-lLmgYg/spiceypy/cspice. Attempting to Download CSPICE For you:
  Gathering information...
  ('SYSTEM:   ', 'Linux')
  ('PROCESSOR:', '')
  ('MACHINE:  ', '32bit')
  Downloading CSPICE for PC_Linux_GCC_32bit...
  Unpacking... (this may take some time!)
  Host OS: Linux
  /usr/bin/ld: F77_aloc.o: Relocations in generic ELF (EM: 3)
  F77_aloc.o: error adding symbols: File in wrong format
  collect2: error: ld returned 1 exit status
  Error: compilation of shared spice.so build exit status: ('256',)
  
  ----------------------------------------
  Failed building wheel for spiceypy
  Running setup.py clean for spiceypy
Failed to build spiceypy
Installing collected packages: spiceypy
  Running setup.py install for spiceypy ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lLmgYg/spiceypy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-kTpUhc-record/install-record.txt --single-version-externally-managed --compile:
    running install
    ('Checking the path', '/tmp/pip-build-lLmgYg/spiceypy/cspice')
    Host OS: Linux
    /usr/bin/ld: F77_aloc.o: Relocations in generic ELF (EM: 3)
    F77_aloc.o: error adding symbols: File in wrong format
    collect2: error: ld returned 1 exit status
    Error: compilation of shared spice.so build exit status: ('256',)
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-lLmgYg/spiceypy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-kTpUhc-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-lLmgYg/spiceypy/

**Comment by AndrewAnnex** [comment]
so Spice as-far-as-I-know does not support ARM processors, and certainly the compilation step I have in spiceypy for mac/linux computers would not work for Raspian. I would suggest first trying to download and build a cspice shared library from scratch on Raspian. If it is possible then I can look into adding that logic into spiceypy or way to provide the shared-library as a runtime or setup time parameter.

could you explain why you are planning to use a raspberry Pi?

**Comment by CAReeser** [comment]
I am building an Orerry with 24 steppers and 6 tinyG controllers. The PI seems like an obvious choice. Is there an alternative platform I should consider that supports your build? Would you consider building an ARM version for $$ or do you know anyone that might take this on. creeser@gmail.com

**Comment by CAReeser** [comment]
spice library is not compiled for ARM processor.

**Comment by CAReeser** [comment]
Creating a cspice shared library on the Pi3.

**Comment by CAReeser** [comment]
Andrew,
Asked Charles Acton at NASA and he forwarded the request to folks at
Arizona State who have already compiled on the RaspberryPi3.
Will keep you updated.

Cliff

**Comment by CAReeser** [comment]
Andrew,
Received libcspice.a (N0066) 7 megs compiled on the RPi from people at ASU. Seems others are using SPICE on the ARM.  Is this what you need? I can email the file if you send an email address.
Thanks,
Cliff 
creeser@gmail.com
