### ISSUE TITLE
Pip install can't create cspice.dll

### ISSUE THREAD

**Issue by JosephVolosin** [AndrewAnnex/SpiceyPy#250]
Here's my cmd output:

> C:\Users\Joseph>pip install --trusted-host pypi.python.org --no-cache-dir SpiceyPy
> Collecting SpiceyPy
>   Downloading spiceypy-2.1.0.tar.gz (113kB)
>     100% |################################| 122kB 644kB/s
> Requirement already satisfied: numpy>=1.12.0 in c:\python27\lib\site-packages (from SpiceyPy)
> Requirement already satisfied: six>=1.9.0 in c:\python27\lib\site-packages (from SpiceyPy)
> Requirement already satisfied: certifi>=2017.1.23 in c:\python27\lib\site-packages (from SpiceyPy)
> Installing collected packages: SpiceyPy
>   Running setup.py install for SpiceyPy ... error
>     Complete output from command c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\Joseph\\appdata\\local\\temp\\pip-build-ggq3ox\\
> SpiceyPy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().re
> place('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --r
> ecord c:\users\Joseph\appdata\local\temp\pip-cti7uu-record\install-record.txt --
> single-version-externally-managed --compile:
>     running install
>     ('Checking the path', 'c:\\users\\Joseph\\appdata\\local\\temp\\pip-build-ggq3ox\\SpiceyPy\\cspice')
>     Unable to find CSPICE at c:\users\Joseph\appdata\local\temp\pip-build-ggq3ox\SpiceyPy\cspice. Attempting to Download CSPICE For you:
>     Gathering information...
>     ('SYSTEM:   ', 'Windows')
>     ('PROCESSOR:', 'Intel64 Family 6 Model 94 Stepping 3, GenuineIntel')
>     ('MACHINE:  ', '32bit')
>     Downloading CSPICE for PC_Windows_VisualC_32bit...
>     Unpacking... (this may take some time!)
>     Host OS: Windows
> c:\users\Joseph\appdata\local\temp\pip-build-ggq3ox\SpiceyPy\cspice\src\cspice>rem Running makeDynamicSpice.bat, this may take some time (a minute or two) .
> 
> 
> c:\users\Joseph\appdata\local\temp\pip-build-ggq3ox\SpiceyPy\cspice\src\cspi
> ce>rem Finished Compiling, starting to Link spice.
> 
> c:\users\Joseph\appdata\local\temp\pip-build-ggq3ox\SpiceyPy\cspice\src\cspice>rem Finished Linking Spice, makeDynamicSpice.bat completed.
> Attempting to move: c:\users\Joseph\appdata\local\temp\pip-build-ggq3ox\Spic
> eyPy\cspice\src\cspice\cspice.dll   to: c:\users\Joseph\appdata\local\temp\pip-b
> uild-ggq3ox\SpiceyPy\spiceypy\utils\cspice.dll
>     cspice.dll file not found, what happend?: [Error 2] The system cannot find t
> he file specified
> 
> Command "c:\python27\python.exe -u -c "import setuptools, tokenize;__file__='c:\
> \users\\Joseph\\appdata\\local\\temp\\pip-build-ggq3ox\\SpiceyPy\\setup.py';f=ge
> tattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.cl
> ose();exec(compile(code, __file__, 'exec'))" install --record c:\users\Joseph\ap
> pdata\local\temp\pip-cti7uu-record\install-record.txt --single-version-externall
> y-managed --compile" failed with error code 1 in c:\users\Joseph\appdata\local\t
> emp\pip-build-ggq3ox\SpiceyPy\
> 

Looks like the pip install's setup.py gets to running the bat file to create cspice.dll but doesn't create it? I don't see any error thrown within the bat file running which makes me think it's properly running.. I tried using the answer to another similar issue by adding the --no-cache-dir argument to pip but it didn't seem to help.

**Comment by AndrewAnnex** [comment]
Since you are using windows please first try the regular pip install command from the documentation. This should install the prebuilt python wheel that is available from pypi. 

Let me know if that works

-Andrew Annex

**Comment by JosephVolosin** [comment]
On a call of,  `pip install spiceypy`, I get an SSL error which I assume is caused from company Wi-Fi complications with the install. Tried through Conda and it gave me a similar SSL error. I'm able to make it work through using the `--trusted-host` option on pip. After some more digging I found this computer's version of setuptools is a little outdated (version 28); not sure if this is causing an issue.

**Comment by AndrewAnnex** [comment]
At first glance the ssl issue sounds like a well known issue with the Python.org Python distribution for macOS, but since you are using windows I would have to see the ssl error and know more about what python you are using like is it an anaconda or miniconda and how old it is. 

But for now try just downloading the python wheel from https://pypi.org/project/spiceypy/#files and installing it directly.

-Andrew Annex

**Comment by JosephVolosin** [comment]
Is there a 32-bit version of the wheel available? Trying the cp27 wheel gives a '.. is not a supported wheel on this platform.' error (current machine and python install are both 32-bit).

Here's the SSL errors and some more information, pip and conda respectively:
`  Could not fetch URL https://pypi.python.org/simple/spiceypy/: There was a problem confirming the ssl certificate: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661) - skipping
  Could not find a version that satisfies the requirement spiceypy (from versions: )
No matching distribution found for spiceypy`
on pip 9.0.1, python 2.7

`Solving environment: failed
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <http://conda.anaconda.com/andrewannex/win-32/repodata.json>
Elapsed: -
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
ConnectionError(MaxRetryError("HTTPConnectionPool(host='conda.anaconda.com', port=80): Max retries exceeded with url: /a
ndrewannex/win-32/repodata.json (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x07C56E70>:
 Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))",),)`
using miniconda (vers. 4.4.7) on python 2.7

**Comment by AndrewAnnex** [comment]
No... while it isn’t impossible to make one, it is just not something I saw much value in working on for a number of reasons. 

It isn’t worth my time helping windows users through the process of setting up visual studio for building spiceypy as it is fairly complicated. If you really have no choice look at the appveyor yaml file or just work out how to manually build the cspice dll and then copy and paste things to the correct directories.

I think 64 bit operating systems became mainstream by 2010, so if your computer is newer than that maybe you have a 32 bit python installed by mistake?

-Andrew Annex

**Comment by JosephVolosin** [comment]
Got it working through the wheel build with Python 3.6 (64 bit this time), thanks for the leads and help! (and sorry for the dumb mistake on my part)
