### ISSUE TITLE
DSK routines

### ISSUE THREAD

**Issue by konwill** [AndrewAnnex/SpiceyPy#260]
Hello, 

I am trying to work a routinge with DSK, namely  the dskxv. It works fine with a single vertex and direction vector. However, providing for both a 4x3 float Matrix (as numpy arrays) does not properly work. Only the first vector of the matrices is evaluated and results returned. All others are returned with false. Though changing the vertex and direction vectors within the array to the first spot will result in a correct results for the first vector again but not for the others.
Could it be that the cspice.dll is not build correctly? I have tested and debugged what arrives at the dskxv routine. All correct as far as I can see. But after the call 
libspice.dskxv_c(pri, target, nsurf, srflst, et, fixref, nray, vtxarr, dirarr, xptarr, fndarr)
it goes wrong.

Best,
konwill

**Comment by AndrewAnnex** [comment]
I won’t be able to directly examine this for a few days, it sounds like it could be a issue with how I am wrapping the function so it would not be related to the dll. It sounds like you can work around this by using a loop for now.

-Andrew Annex

**Comment by konwill** [comment]
Thanks for the quick reply. I do looping at the moment. Was hoping to speed up things by calling spice c implemented routine fewer times.

**Comment by AndrewAnnex** [comment]
I looked into this for a bit and I don't currently an issue with my wrapping of the function that could explain this problem.

**Comment by AndrewAnnex** [comment]
so I think I have identified the issue however the fix will require a bit more thought and will also mean a new release will be made so the patch is probably a week or two out.
