### ISSUE TITLE
5 digit years not covered in timout or tpictr

### ISSUE THREAD

**Issue by CAReeser** [AndrewAnnex/SpiceyPy#266]
Not sure if this is a spice or a spiceypy issue, but years earlier than 9999 B.C and later than 9999A.D are not functional in functions timout or tpictr. SPICE de431 begin_date = 13201 B.C. 05-06 00:00' and ends at 
'17191 A.D. 03-15 00:00' so I would tend to think that their functions would cover those dates....Looks like it is just an issue with the year format, as the month/day/time is correct as seen below.

Example:
input date: 12018 B.C. 07/11 12:19:27
et of input date = -4.42317281992e+11
output picture of date using tpictr:     'YYYY ERA MM/DD HR:MN:SC'
string from timout using date and picture:   **** B.C. 07/11 12:19:27

**Comment by jdiazdelrio** [comment]
Hi Cliff,

it is an SPICE limitation. A workaround, depending on the time
system you want to use for the output string is the following:

  - UTC time system: use et2utc, with 'C' as format. With the input time
    you have provided in your email, you should be getting the following
    time string: 12018 B.C. JUL 11 12:19:26.815

  - TDB/ET time system: use etcal. With your input time, the output string
    should be:   12018 B.C. JUL 11 12:20:08.000

Hope this helps.

Regards,
  Jorge 

Jorge Diaz del Rio
ODC Space
www.odcspace.com

**Comment by AndrewAnnex** [comment]
I think this solves the issue, so I will close this in a few days if @CAReeser doesn't confirm.

**Comment by CAReeser** [comment]
I tested et2utc and it works perfectly with 5 digit years. Thanks for your help. Pls close this issue. 

Cliff
