### ISSUE TITLE
OSError: ../spiceypy/utils/spice.so: cannot open shared object file: No such file or directory when trying to import spiceypy in linux

### ISSUE THREAD

**Issue by ZhenhuaJing** [AndrewAnnex/SpiceyPy#268]
Hey Andrew,

I have already seen #240 and #256, Probably due to China's network, I can't use `pip install spiceypy —no-cache-dir` in linux, so I installed the spice using `python setup.py install`. This process seems to be no problem, problems arise when I import the spiceypy:
```
import spiceypy as spice
  File "/nas02/yangtao/Python-3.6.4/lib/python3.6/site-packages/spiceypy/__init__.py", line 25, in <module>
    from .spiceypy import *
  File "/nas02/yangtao/Python-3.6.4/lib/python3.6/site-packages/spiceypy/spiceypy.py", line 27, in <module>
    from .utils.libspicehelper import libspice
  File "/nas02/yangtao/Python-3.6.4/lib/python3.6/site-packages/spiceypy/utils/libspicehelper.py", line 34, in <module>
    libspice = CDLL(sitePath)
  File "/nas02/yangtao/Python-3.6.4/lib/python3.6/ctypes/__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /nas02/yangtao/Python-3.6.4/lib/python3.6/site-packages/spiceypy/utils/spice.so: cannot open shared object file: No such file or directory
```
Is there any other solution without using `pip install spiceypy —no-cache-dir`? Any help would be appreciated, thanks!

**Comment by AndrewAnnex** [comment]
my guess is that you need to download cspice manually and then try installing again, otherwise it is very easy on linux to build the shared library (see steps in InstallCSpice class) and then you can just place it in the site-packages location required.

**Comment by ZhenhuaJing** [comment]
Thanks for your reply.
Yes, when I first installed using `python setup.py install`, I manually downloaded the corresponding version of cspice and installd it in the corresponding directory using the following command.
```
$ chmod u+x importCSpice.csh
$ ./importCSpice.csh
```
Is it because I install CSpice wrongly? I did not get the shared library. Please forgive me for not being good at c language.
