### ISSUE TITLE
Add python 3.7 wheel

### ISSUE THREAD

**Issue by dstansby** [AndrewAnnex/SpiceyPy#269]
I'm having some trouble installing SpiceyPy on windows in a python 3.7 environment; I believe it's because it is trying to build from source because no windows 3.7 wheels are available. Would it be possible to have one made and uploaded to pypi?

**Comment by AndrewAnnex** [comment]
at the moment the process I have for building windows wheels is highly coupled with the process that builds anaconda packages on windows so some work is needed to either decouple the builds or to improve them to apply updates to miniconda at runtime. It may take me a few days/ a week or two

**Comment by AndrewAnnex** [comment]
@dstansby I just uploaded the windows 3.7 wheel to pypi, try installing now. I will reopen the issue if you run into further issues with install.

**Comment by dstansby** [comment]
Brilliant, thanks a lot! Will give them a spin.
