### ISSUE TITLE
Failed building wheel for spiceypy

### ISSUE THREAD

**Issue by kd7uiy** [AndrewAnnex/SpiceyPy#279]
Just tried to install this today. It seemed successful, and is in the pip list, but there was an error "Failed building wheel for spiceypy", and it doesn't seem to import. Any idea what is going on?

C:\Users\tuvas\Desktop\Python\Interplanetary>pip install -U spiceypy
Collecting spiceypy
  Using cached https://files.pythonhosted.org/packages/aa/75/a10785f356f58c784979027b474713951aebc95be228e932b73d021009bf/spiceypy-2.1.2.tar.gz
Requirement already satisfied, skipping upgrade: numpy>=1.12.0 in c:\users\tuvas\appdata\local\programs\python\python36-32\lib\site-packages (from spiceypy) (1.16.0)
Requirement already satisfied, skipping upgrade: six>=1.9.0 in c:\users\tuvas\appdata\local\programs\python\python36-32\lib\site-packages (from spiceypy) (1.12.0)
Requirement already satisfied, skipping upgrade: certifi>=2017.1.23 in c:\users\tuvas\appdata\local\programs\python\python36-32\lib\site-packages (from spiceypy) (2018.11.29)
Building wheels for collected packages: spiceypy
  Running setup.py bdist_wheel for spiceypy ... error
  Complete output from command c:\users\tuvas\appdata\local\programs\python\python36-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\tuvas\\AppData\\Local\\Temp\\pip-install-emm27kck\\spiceypy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\tuvas\AppData\Local\Temp\pip-wheel-b6se0l9s --python-tag cp36:
  Wheel is Present
  running bdist_wheel
  running build
  running build_py
  Checking the path C:\Users\tuvas\AppData\Local\Temp\pip-install-emm27kck\spiceypy\cspice
  Unable to find CSPICE at C:\Users\tuvas\AppData\Local\Temp\pip-install-emm27kck\spiceypy\cspice. Attempting to Download CSPICE For you:
  Gathering information...
  SYSTEM:    Windows
  PROCESSOR: AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
  MACHINE:   32bit
  Downloading CSPICE for PC_Windows_VisualC_32bit...
  Unpacking... (this may take some time!)
  Host OS: Windows

  C:\Users\tuvas\AppData\Local\Temp\pip-install-emm27kck\spiceypy\cspice\src\cspice>rem Running makeDynamicSpice.bat, this may take some time (a minute or two) ...
  'cl' is not recognized as an internal or external command,
  operable program or batch file.
  'cl' is not recognized as an internal or external command,
  operable program or batch file.
..... (Repeats about 100 times)
  'cl' is not recognized as an internal or external command,
  operable program or batch file.
  'cl' is not recognized as an internal or external command,
  operable program or batch file.
  'cl' is not recognized as an internal or external command,
  operable program or batch file.
  File Not Found

  C:\Users\tuvas\AppData\Local\Temp\pip-install-emm27kck\spiceypy\cspice\src\cspice>rem Finished Compiling, starting to Link spice.
  'link' is not recognized as an internal or external command,
  operable program or batch file.

  C:\Users\tuvas\AppData\Local\Temp\pip-install-emm27kck\spiceypy\cspice\src\cspice>rem Finished Linking Spice, makeDynamicSpice.bat completed.
  Attempting to move: C:\Users\tuvas\AppData\Local\Temp\pip-install-emm27kck\spiceypy\cspice\src\cspice\cspice.dll   to: C:\Users\tuvas\AppData\Local\Temp\pip-install-emm27kck\spiceypy\spiceypy\utils\cspice.dll
  cspice.dll file not found, what happend?: [WinError 2] The system cannot find the file specified: 'C:\\Users\\tuvas\\AppData\\Local\\Temp\\pip-install-emm27kck\\spiceypy\\cspice\\src\\cspice\\cspice.dll' -> 'C:\\Users\\tuvas\\AppData\\Local\\Temp\\pip-install-emm27kck\\spiceypy\\spiceypy\\utils\\cspice.dll'

  ----------------------------------------
  Failed building wheel for spiceypy
  Running setup.py clean for spiceypy
Failed to build spiceypy
Installing collected packages: spiceypy
  Running setup.py install for spiceypy ... done
Successfully installed spiceypy-2.1.2

C:\Users\tuvas\Desktop\Python\Interplanetary>python SpiceDataParsing.py
Traceback (most recent call last):
  File "SpiceDataParsing.py", line 1, in <module>
    import spiceypy as spice
  File "C:\Users\tuvas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spiceypy\__init__.py", line 25, in <module>
    from .spiceypy import *
  File "C:\Users\tuvas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spiceypy\spiceypy.py", line 27, in <module>
    from .utils.libspicehelper import libspice
  File "C:\Users\tuvas\AppData\Local\Programs\Python\Python36-32\lib\site-packages\spiceypy\utils\libspicehelper.py", line 34, in <module>
    libspice = CDLL(sitePath)
  File "C:\Users\tuvas\AppData\Local\Programs\Python\Python36-32\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

C:\Users\tuvas\Desktop\Python\Interplanetary>

**Comment by kd7uiy** [comment]
It seems like the key to this is the "'cl' is not recognized as an internal or external command," . Googling that indicates that it is a Visual Studio thing, used in installing CSPICE. Running the command in a developer command prompt for visual studio, and I think I've managed to install it correctly. 

As to helping others with this same situation, maybe making mention of making sure that visual studio is on their path or something like that?

**Comment by AndrewAnnex** [comment]
I think you are using a 32bit system so that is why spiceypy did not install from the wheels on pypi. Can you confirm? I no longer auto build 32bit versions of the project.

-Andrew Annex

**Comment by kd7uiy** [comment]
I am actually using the 32 bit python, hadn't realized that. Huh. That now makes sense.
