### ISSUE TITLE
Dskx02 error

### ISSUE THREAD

**Issue by pedrohasselmann** [AndrewAnnex/SpiceyPy#287]
HI Andrew,

I have spiceypy 2.1.2 running on Linux installed through pip command.
I also have CSPICE N66 installed.

I'm trying to run a dsk function called dskx02 but I get the following error:

```
     plate, xpt, f = spice.dskx02(handle, dladsc, haya2pos, ray)
 TypeError: dskx02() takes no arguments (4 given)
```

When I remove all arguments I get NotImplementError.

However I'm surely aware that my script works because it was written and tested by a colleague using either Linux or MacOS.

**Comment by AndrewAnnex** [comment]
@pedrohasselmann you must not actually be running 2.1.2, installing N66 outside of spiceypy has no bearing on this problem. I would recommend making sure you aren't crossing python installations (ie pip linked to a different python than you are using when you get the error) and actually going into the spiceypy.py file to look for dskx02 (I added those functions in late 2017 if my quick look at the log is correct).

**Comment by pedrohasselmann** [comment]
Indeed,

It was calling an older version (2.0.0)  install at ~./local for some reason I don't know. 
Everything is fine now, thanks again, Andrew. Great tool you have here.
