### ISSUE TITLE
spiceypy.bodvrd question

### ISSUE THREAD

**Issue by macicco** [AndrewAnnex/SpiceyPy#291]
**Describe the bug**

Calling spiceypy.bodvrd ('EARTH', "GM", 5)

Expected  gravitational parameter for Earth , but...:

_**Toolkit version: N0066

SPICE(KERNELVARNOTFOUND) --
The Variable Was not Found in the Kernel Pool.
The variable BODY399_GM could not be found in the kernel pool.

bodvrd_c --> BODVRD**_

**Desktop (please complete the following information):**
 - SpiceyPy Version [CSPICE_N0066]
 - OS: [ Linux, Ubuntu 18.4 LTS]
 - OS Architecture [64bit]
 - Python Version [3.6.5, etc]
 - Python Architecture [64bit,]

**Additional context**
Tried same for Sun and same type error again

**Comment by AndrewAnnex** [comment]
You need to load a kernel for the gravitational parameters. loading this kernel: https://naif.jpl.nasa.gov/pub/naif/generic_kernels/pck/Gravity.tpc worked for me

**Comment by macicco** [comment]
Ok, so I use 'spiceypy.spiceypy.furnsh(path)' to do that?

**Comment by macicco** [comment]
Worked! 

"GMs = spiceypy.spiceypy.bodvrd('SUN', "GM", 5) 

(1, array([1.3271244e+11, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00]))

"

Thanks!
