### ISSUE TITLE
Wrappers for low level frame functions

### ISSUE THREAD

**Issue by jessemapel** [AndrewAnnex/SpiceyPy#295]
**Is your feature request related to a problem? Please describe.**
There are a handful of low level subroutines in the SPICE library that provide detailed frame information. They are available in C SPICE, but are not wrapped in SpicePy.

**Describe the solution you'd like**
Specifically, I'm interested in these two functions:

[tkfram](https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/spicelib/tkfram.html)
[ckfrot](https://naif.jpl.nasa.gov/pub/naif/toolkit_docs/FORTRAN/spicelib/ckfrot.html)

The piece of information I am most interested in is the ID of the frame that a frame is define from. I.E., frame A is defined as a fixed rotation from frame B. Providing Python bindings for these functions would be very helpful for working with complex rotations.

**Describe alternatives you've considered**
I can wrap these functions in code where I need them, but I figure it makes more sense for them to be wrapped alongside the rest of C SPICE.

Another alternative would be to just manually determine the frame chain for the reference frames I am interested in. This is probably 100-200 frames across dozens of instruments and missions, so I'd rather not do this.

**Additional context**
These functions are not documented in the NAIF C SPICE docs, but they are available in libcspice.

```
(ale) igswzawglt1183:ale jmapel$ nm -gU /Users/jmapel/miniconda3/envs/ale/lib/libcspice.dylib | grep "tkfram"
000000000012ca90 T _tkfram_
```

```
(ale) igswzawglt1183:ale jmapel$ nm -gU /Users/jmapel/miniconda3/envs/ale/lib/libcspice.dylib | grep "ckfrot"
000000000000fd30 T _ckfrot_
```

These functions are also used in ISIS to determine frame chains (https://github.com/USGS-Astrogeology/ISIS3/blob/dev/isis/src/base/objs/SpiceRotation/SpiceRotation.cpp#L2579).

The USGS Astrogeology Science Center is will to implement this and provide a PR. I would like some input as per should this be in SpiceyPy or is there a better way to determine frame chains.

**Comment by AndrewAnnex** [comment]
Hey Jesse,

A contribution would be welcome, just follow the style and ensure there are unit tests.

Thanks
-Andrew

**Comment by AndrewAnnex** [comment]
I am also wondering why these two functions are not "officially" wrapped in cspice, does FRINFO provide the info needed? Again, I am happy to review the PR but maybe you should ask the naif directly as well.

**Comment by jessemapel** [comment]
I'll re-open this once I get around to writing it!
