### ISSUE TITLE
Navigated Image

### ISSUE THREAD

**Issue by rgoalcast** [AndrewAnnex/SpiceyPy#299]
Respected Sir, 
Sir, How can planetary images are being navigated using Spicepy software as shown in attached image ?

**Comment by rgoalcast** [comment]
Sir, How can planetary images are being navigated using Spicepy software as shown in attached image ?

**Comment by rgoalcast** [comment]
Respected Sir,
Sir, How can planetary images are being navigated using Spicepy software as shown in figure 1 of paper 
<https://www.sciencedirect.com/science/article/pii/S0019103517301501>.

**Comment by AndrewAnnex** [comment]
I suggest you ask the authors of the paper, in their paper they say they use another application called PLIA

**Comment by rgoalcast** [comment]
Sir in this absrtact 
https://meetingorganizer.copernicus.org/EPSC2018/EPSC2018-337.pdf

they have used Python to navigate Mars Images, Pls. Sir let me know ?
