### ISSUE TITLE
Help required

### ISSUE THREAD

**Issue by rgoalcast** [AndrewAnnex/SpiceyPy#300]
Sir in this absrtact
https://meetingorganizer.copernicus.org/EPSC2018/EPSC2018-337.pdf

they have used Python to navigate Mars Images, Pls. Sir let me know ?

**Comment by AndrewAnnex** [comment]
No, this is not an issue that I can help you with. Please contact the NAIF directly instead at https://naif.jpl.nasa.gov/naif/contactinfo.html

-Andrew Annex
