### ISSUE TITLE
function 'ckfrot_' not found

### ISSUE THREAD

**Issue by RL4215** [AndrewAnnex/SpiceyPy#305]
I am using Anaconda with python 3.7 and installed spiceypy with conda. I try to import the package and get the error "function 'ckfrot_' not found".

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Ronan\Anaconda3\lib\site-packages\spiceypy\__init__.py", line 25, in <module>
    from .spiceypy import *
  File "C:\Users\Ronan\Anaconda3\lib\site-packages\spiceypy\spiceypy.py", line 28, in <module>
    from .utils.libspicehelper import libspice
  File "C:\Users\Ronan\Anaconda3\lib\site-packages\spiceypy\utils\libspicehelper.py", line 99, in <module>
    libspice.ckfrot_.argtypes = [c_int_p, c_double_p, (c_double * 3) * 3, c_int_p, c_int_p]
  File "C:\Users\Ronan\Anaconda3\lib\ctypes\__init__.py", line 369, in __getattr__
    func = self.__getitem__(name)
  File "C:\Users\Ronan\Anaconda3\lib\ctypes\__init__.py", line 374, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'ckfrot_' not found

I don't want to use this function, its just that the import fails.

**Comment by AndrewAnnex** [comment]
Thanks for the bug report, this is likely an issue with the conda-forge cspice-feedstock which I forgot to have updated after the most recent release. I’ll reply once that repository has been updated, at which point you will need to update to the newer version of cspice from conda forge

-Andrew Annex

**Comment by LukeBarnard** [comment]
Yup, I'm having the same issue. So do you think I could avoid this by installing from source?

**Comment by AndrewAnnex** [comment]
windows users should install spiceypy using `pip` until the conda-forge distribution is fixed, the prebuilt wheels for windows should be used for now instead of installing from source which is a fairly complicated thing for windows users as discussed in prior issues

**Comment by AndrewAnnex** [comment]
an update to conda-build has been merged that should allow me eventually to patch the conda-forge cspice package, but it is not clear when the next release for that repository will be made.

**Comment by RL4215** [comment]
I installed with pip and it works now, thank you

**Comment by MrZombie69232** [comment]
I tried installing using pip but still getting the error while trying to import the library 

AttributeError: function 'ckfrot_' not found

**Comment by AndrewAnnex** [comment]
Make sure the pip command you used is installing spiceypy to the same python interpreter you used and that you didn’t install it with conda to the same interpreter. This issue is only relevant to the conda forge distribution of spiceypy 

-Andrew Annex

**Comment by MrZombie69232** [comment]
I installed it with same interpreter but still having problem with spiceypy and planets

**Comment by AndrewAnnex** [comment]
Interesting, please run both of these commands “pip -V” and “pip list” 

-Andrew Annex

**Comment by MrZombie69232** [comment]
pip 19.2.3 from C:\Conda\lib\site-packages\pip (python 3.7)

(base) C:\WINDOWS\system32>pip list
Package                Version
---------------------- -----------
asn1crypto             1.0.1
astropy                3.2.2
atomicwrites           1.3.0
attrs                  19.3.0
backcall               0.1.0
bleach                 3.1.0
certifi                2019.9.11
cffi                   1.12.3
chardet                3.0.4
Click                  7.0
click-plugins          1.1.1
cligj                  0.5.0
colorama               0.4.1
conda                  4.7.12
conda-package-handling 1.6.0
cryptography           2.7
cycler                 0.10.0
decorator              4.4.0
defusedxml             0.6.0
entrypoints            0.3
Fiona                  1.8.9.post2
GDAL                   3.0.1
geopandas              0.6.1
heat1d                 0.1.4
idna                   2.8
importlib-metadata     0.23
ipykernel              5.1.3
ipython                7.9.0
ipython-genutils       0.2.0
ipywidgets             7.5.1
jedi                   0.15.1
Jinja2                 2.10.3
jsonschema             3.1.1
jupyter-client         5.3.3
jupyter-console        6.0.0
jupyter-core           4.5.0
kiwisolver             1.1.0
MarkupSafe             1.1.1
matplotlib             3.1.1
menuinst               1.4.16
mistune                0.8.4
mkl-service            2.3.0
more-itertools         7.2.0
munch                  2.3.2
nbconvert              5.6.1
nbformat               4.4.0
notebook               6.0.1
numpy                  1.17.3
packaging              19.2
pandas                 0.25.2
pandocfilters          1.4.2
parso                  0.5.1
pickleshare            0.7.5
pip                    19.2.3
planets                0.4.5
pluggy                 0.13.0
prometheus-client      0.7.1
prompt-toolkit         2.0.10
psutil                 5.6.3
py                     1.8.0
pycosat                0.6.3
pycparser              2.19
Pygments               2.4.2
pyOpenSSL              19.0.0
pyparsing              2.4.2
pyproj                 2.4.0
PyQt5                  5.12.3
PyQt5-sip              4.19.18
PyQtWebEngine          5.12.1
pyrsistent             0.15.4
PySocks                1.7.1
pytest                 5.2.2
pytest-arraydiff       0.3
pytest-astropy         0.5.0
pytest-doctestplus     0.4.0
pytest-openfiles       0.4.0
pytest-remotedata      0.3.1
python-dateutil        2.8.0
pytz                   2019.3
pywin32                223
pywinpty               0.5.5
pyzmq                  18.1.0
qtconsole              4.5.5
requests               2.22.0
Rtree                  0.8.3
ruamel-yaml            0.15.46
scipy                  1.3.1
Send2Trash             1.5.0
setuptools             41.4.0
Shapely                1.6.4.post2
six                    1.12.0
spicer                 0.4.1
spiceypy               2.3.1
terminado              0.8.2
testpath               0.4.2
tornado                6.0.3
tqdm                   4.36.1
traitlets              4.3.3
urllib3                1.24.2
wcwidth                0.1.7
webencodings           0.5.1
wheel                  0.33.6
widgetsnbextension     3.5.1
win-inet-pton          1.1.0
wincertstore           0.2
zipp                   0.6.0

above are the results after those commands

**Comment by AndrewAnnex** [comment]
It looks like you are running anaconda, try uninstalling spiceypy using conda then uninstall using pip, then finally reinstall using pip

-Andrew Annex

**Comment by MrZombie69232** [comment]
I did and now while importing I am getting following error while trying to import planets 

HTTPError: HTTP Error 404: Not Found

**Comment by AndrewAnnex** [comment]
@MrZombie69232 then you have solved your issue with spiceypy, I am not sure what "planets" is but if it is this python package: https://github.com/michaelaye/planets, then you should open an issue there

**Comment by MrZombie69232** [comment]
Thanks a lot for your quick response .

**Comment by AndrewAnnex** [comment]
Finally can close this issue, https://github.com/conda-forge/cspice-feedstock/pull/12 was just merged after the new release of conda-build, which allowed new windows artifacts for cspice to be compiled. please wait a few minutes until the CI builds finish, files can be found here https://anaconda.org/conda-forge/cspice/files

**Comment by LukeBarnard** [comment]
Thanks Andrew!
