### ISSUE TITLE
Numpy string support 

### ISSUE THREAD

**Issue by michaelaye** [AndrewAnnex/SpiceyPy#309]
When the spice function requires the use of the Python string method, it does not currently work to provide a numpy array with the strings, e.g.:

```python
scid = -64
arr = np.array(['3/0597205898.09324', '3/0597205898.09952', '3/0597205898.10580',
       '3/0597205898.11836', '3/0597205898.12464'])
spice.scencd(scid, arr)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-62-71689f28cd51> in <module>
----> 1 spice.scencd(scid, arr)

~/miniconda3/envs/py37/lib/python3.7/site-packages/spiceypy/spiceypy.py in with_errcheck(*args, **kwargs)
     75     def with_errcheck(*args, **kwargs):
     76         try:
---> 77             res = f(*args, **kwargs)
     78             checkForSpiceError(f)
     79             return res

~/miniconda3/envs/py37/lib/python3.7/site-packages/spiceypy/spiceypy.py in scencd(sc, sclkch, MXPART)
  10984     """
  10985     sc = ctypes.c_int(sc)
> 10986     sclkch = stypes.stringToCharP(sclkch)
  10987     sclkdp = ctypes.c_double()
  10988     libspice.scencd_c(sc, sclkch, ctypes.byref(sclkdp))

~/miniconda3/envs/py37/lib/python3.7/site-packages/spiceypy/utils/support_types.py in stringToCharP(inobject, inlen)
    195     if isinstance(inobject, int):
    196         return stringToCharP(" " * inobject)
--> 197     return c_char_p(inobject.encode(encoding='UTF-8'))
    198 
    199 

AttributeError: 'numpy.ndarray' object has no attribute 'encode'
```

That's because a Python string has the `encode` method build in, but the spiceypy function does not reach it via the numpy array.

**Describe the solution you'd like**
Above call should work. ;)

**Describe alternatives you've considered**
My work around is:

```python
encodedSclk = [spice.scencd(scid, item) for item in arr]
```

**Comment by AndrewAnnex** [comment]
So although numpy arrays have the ability to contain string and object data types I have never anticipated a user to use numpy for strings. Numpy is synonymous with numerical arrays, I’ll research this more but is this significantly better than using lists instead?

-Andrew Annex

**Comment by michaelaye** [comment]
It is, in the context of using pandas as a data container.
When one is reading large XML data files, for example from OREX OLA, using `pds4_tools` the return is a pandas DataFrame.

And some of this columns simply are strings, there's no way around that.

**Comment by michaelaye** [comment]
Let me correct myself: I am using pds4_tools like that, although it does not directly return pandas:

```python
df = pd.DataFrame(pds4_read(str(self.l0_path))[0].data)
```

However, I think pandas is immensely productive in dealing with raw instrument data, due to its immediate table view and efficient array manipulation, so I think this should be supported.

**Comment by michaelaye** [comment]
I will put in PR's for the other 2 functions, if you could have a look how to do this with strings, would be great?

**Comment by AndrewAnnex** [comment]
this function will need to be vectorized to handle the numpy array as given in the example code above, fyi to myself

**Comment by AndrewAnnex** [comment]
also as a fyi to myself there are a few different ways strings are used in cspice, typically parameters are given as a 1d strings but in some cases 2d string arrays are parameters not used in loops.

**Comment by AndrewAnnex** [comment]
I'm closing this issue as #310 supersedes it now that underlying issue for support of strings in numpy arrays has been fixed
