### ISSUE TITLE
Return numpy.array when array comes in for spkpos and similar functions

### ISSUE THREAD

**Issue by michaelaye** [AndrewAnnex/SpiceyPy#311]
I was wondering if it wouldn't be more efficient to return an 2D numpy array instead of tuples for some of the position/attitude calculators.

For example,

spiceypy.spkpos currently returns a tuple when `et` has the __iter__ attribute:

```python
scPos = spice.spkpos("OSIRIS-REX", arr, "IAU_BENNU", "NONE", "BENNU")
scPos

([array([ 1.7448318926770625, -0.8504531567796572,  7.425652879256819 ]),
  array([ 1.7448267627978935, -0.8504593575834141,  7.425652934559143 ]),
  array([ 1.7448216329216404, -0.8504655583093308,  7.42565298986146  ]),
  array([ 1.7448113741792106, -0.8504779584415174,  7.425653100453687 ]),
  array([ 1.7448062447402481, -0.8504841584850534,  7.425653155750478 ])],
 [2.5601566831735227e-05,
  2.5601565412065215e-05,
  2.5601563992396694e-05,
  2.5601561153381996e-05,
  2.5601559733859212e-05])

type(scPos)
tuple
```

and I know that I can do:

```python
nparr = np.array(scPos[0])
```
to get a basic numpy array, but isn't it slower to first go through tuples?

**Describe the solution you'd like**
If `spkpos` would simply return a (n, 4) shaped array, users that only need the vectors could simply slice it:

```python
positions = scPos[:, :3]
```

**Describe alternatives you've considered**
My workaround is:

positions = np.array(result[0])

**Additional context**
Just wondering if you slow yourself down too much here. Did you do any performance tests?

**Comment by AndrewAnnex** [comment]
so the way spiceypy does vectorization has been a matter of debate, but a while ago in #192 we found that returning tuples of lists were pretty fast. I think there are cases where different return values have different data types, making a single 2d array the wrong choice. It, however, could make sense to convert returned lists of tuples into 2d arrays for the user (so the scPos would be a tuple of a 2d array and a 1d array). Some benchmarks will be needed to evaluate this.

**Comment by AndrewAnnex** [comment]
I am closing this issue for now as of #333. in the next release the functions will always return a numpy array or a tuple of numpy arrays as discussed here
