### ISSUE TITLE
Problem with documentation generation?

### ISSUE THREAD

**Issue by brad-trantham** [AndrewAnnex/SpiceyPy#319]
Am I missing something or has something happened to the documentation? When I open this page it's only a few lines, rather than the usual lengthy and detailed module documentation.

https://spiceypy.readthedocs.io/en/master/documentation.html#spiceypy-module

**Comment by AndrewAnnex** [comment]
hmm seems to be an issue with the most recent builds, use this link for the most recent docs https://spiceypy.readthedocs.io/en/v2.3.1/documentation.html

**Comment by brad-trantham** [comment]
Perfect, thanks!
