### ISSUE TITLE
ev2lin is noy present in the master version of spiceypy release 2.3.1

### ISSUE THREAD

**Issue by OrbitalMechanic** [AndrewAnnex/SpiceyPy#322]
I reinstalled spiceypy out of the master level in the hope of picking up ev2lin. Alas, it wasn't in the source code that got downloaded (see attached file).

Please advise.

Sam Dupree.

[spiceypy.py.txt](https://github.com/AndrewAnnex/SpiceyPy/files/3867928/spiceypy.py.txt)

**Comment by AndrewAnnex** [comment]
I haven’t made a new release of spiceypy so ev2lin will not be made available through pip until the release or 2.3.2 or 2.4.0 whatever is next. If you clone the repository using fit or download the current master branch source code then you should be able to use ev2lin. The next release is contingent on a few issues at the moment.

-Andrew Annex
