### ISSUE TITLE
test_sct2e encapsulates 2 different functions

### ISSUE THREAD

**Issue by michaelaye** [AndrewAnnex/SpiceyPy#323]
**Describe the bug**

Your test function test_sct2e is relying on the functioning of `et2utc`, which means your test is not encapsulating the actual unit to be tested.

**Expected behavior**
`sct2e` returns a float `et` and reasonable proximity to that float should be tested against.

**Comment by michaelaye** [comment]
A similar issue I see with test_scencd, where the test relies on scdecd to work.

**Comment by AndrewAnnex** [comment]
some functions are tested as an integration tests while others are mostly true unit tests. closing this as a won't fix
