### ISSUE TITLE
Fails to build wheels in macOS Catalina

### ISSUE THREAD

**Issue by jehosafatc** [AndrewAnnex/SpiceyPy#329]
I followed the installation steps to install spiceypy on terminal however, it fails to build the wheels.
I tried the --no-cache-dr way and did not work either. I am running macOS Catalina and Python 3.6 64bit 
this is the result:

pip3 install spiceypy
Collecting spiceypy
  Using cached https://files.pythonhosted.org/packages/2c/4f/1ad7228338bafa481e97080428f2decbf6f41a7c3a67e3dc1d4b140f899f/spiceypy-2.3.1.tar.gz
Requirement already satisfied: setuptools>=38.0.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from spiceypy) (42.0.1)
Requirement already satisfied: six>=1.9.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from spiceypy) (1.13.0)
Requirement already satisfied: certifi>=2017.1.23 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from spiceypy) (2019.9.11)
Requirement already satisfied: numpy>=1.17.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from spiceypy) (1.17.4)
Building wheels for collected packages: spiceypy
  Building wheel for spiceypy (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/setup.py'"'"'; __file__='"'"'/private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-wheel-4jk4z91v --python-tag cp36
       cwd: /private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/
  Complete output (22 lines):
  Wheel is Present
  running bdist_wheel
  running build
  running build_py
  Checking the path /private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/cspice
  Unable to find CSPICE at /private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/cspice. Attempting to Download CSPICE For you:
  Gathering information...
  SYSTEM:    Darwin
  PROCESSOR: i386
  MACHINE:   64bit
  Downloading CSPICE for MacIntel_OSX_AppleC_64bit...
  Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
  Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
  Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
  Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
  Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
  Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
  Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
  Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
  Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
  Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
  Unable to find CSPICE at /private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/cspice. Exiting
  ----------------------------------------
  ERROR: Failed building wheel for spiceypy
  Running setup.py clean for spiceypy
Failed to build spiceypy
Installing collected packages: spiceypy
    Running setup.py install for spiceypy ... error
    ERROR: Command errored out with exit status 1:
     command: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/setup.py'"'"'; __file__='"'"'/private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-record-g95kpcrc/install-record.txt --single-version-externally-managed --compile
         cwd: /private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/
    Complete output (20 lines):
    Wheel is Present
    running install
    Checking the path /private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/cspice
    Unable to find CSPICE at /private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/cspice. Attempting to Download CSPICE For you:
    Gathering information...
    SYSTEM:    Darwin
    PROCESSOR: i386
    MACHINE:   64bit
    Downloading CSPICE for MacIntel_OSX_AppleC_64bit...
    Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
    Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
    Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
    Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
    Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
    Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
    Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
    Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
    Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
    Download failed with URLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:833), trying again after 15 seconds!
    Unable to find CSPICE at /private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/cspice. Exiting
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Library/Frameworks/Python.framework/Versions/3.6/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/setup.py'"'"'; __file__='"'"'/private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-install-jg78qmzl/spiceypy/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/98/kq_bhqr56ndbsx27d1yr6hrm0000gn/T/pip-record-g95kpcrc/install-record.txt --single-version-externally-managed --compile Check the logs for full command output.

**Comment by AndrewAnnex** [comment]
This looks like the ssl handshake error due to outdated openssl and certificates... please read this documentation page to upgrade the certificates: https://spiceypy.readthedocs.io/en/master/installation.html#ssl-alert-handshake-issue. In short, if you downloaded your python distribution from python.org there is a script you must run to update the certificates on your machine.

 If that does not work then possibly something more interesting is happening

**Comment by jehosafatc** [comment]
It worked! thank you so much!!
