### ISSUE TITLE
In the MAVEN Spacecraft, need to Extracting the Orbit number from .orb file. for a given et.

### ISSUE THREAD

**Issue by Sherlock7491** [AndrewAnnex/SpiceyPy#375]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by AndrewAnnex** [comment]
@Sherlock7491 you don't provide any information around this issue and given the subject this sounds like you are looking for a solution to a specific problem external to the scope of spiceypy, I have never seen a MAVEN .orb file so I suspect the MAVEN team would be the place to start to get orbit numbers and date from those files. I'm closing this for now but if others have ideas for solving the specific issue feel free to post code snippets to this issue.
