### ISSUE TITLE
nintvls parameter name in event finder API is not homogeneous 

### ISSUE THREAD

**Issue by salvioli** [AndrewAnnex/SpiceyPy#386]
**Describe the bug**
The parameter nintvls of the event finder API is not always spelled identically, sometimes it appears as nintvls while other times appears as nintvals.
In SPICE documentation it appears to be nintvls

**Comment by AndrewAnnex** [comment]
@salvioli thanks, it looks like only two dozen or so instances of nintvls are present in the code base so it should be easy for me to make it more consistent. The changes will probably not be available however until the next major release of spiceypy, as it would be a breaking change to the api, so it could be a few weeks/months until I decide to make that new release.

**Comment by salvioli** [comment]
No problem, just wanted to point it out. Thanks to you for open sourcing this library!
