### ISSUE TITLE
Strange data artifacts on Juno data 

### ISSUE THREAD

**Issue by gabrielb09** [AndrewAnnex/SpiceyPy#388]
I have been using SpiceyPy (to great effect), to process trajectory information from the Juno Mission. I have been using the subpnt function to gather latitude, longitude and the skpos function to gather the position vectors for Juno during its orbits. For each orbit I use the meta kernel provided by the JADE team. My trajectory results appear to be generally accurate however several orbits have strange artifacts in them. These artifacts appear as large leaps in the the position vector and corresponding jumps in the latitude/longitude data. 

**Expected behavior**
The web based SPICE interface (with the same meta kernel) produces data which is similar to the SpiceyPy output but without the artifacts. (I have attached plots for comparison)

![Unknown](https://user-images.githubusercontent.com/19457532/96160516-143ff400-0ee4-11eb-98eb-9736b7110e6c.png)
![WGC_SubObserverPoint_20201015125306_0](https://user-images.githubusercontent.com/19457532/96161756-adbbd580-0ee5-11eb-97c9-8eaa3935a4b9.png)

![Unknown_2](https://user-images.githubusercontent.com/19457532/96161958-efe51700-0ee5-11eb-9ae1-51d11ca5e579.png)
![WGC_SubObserverPoint_20201015125306_1](https://user-images.githubusercontent.com/19457532/96162052-11460300-0ee6-11eb-9908-05001b74d988.png)

**To Reproduce**
This is the code I've been using to gather the position information:
```
    spice.furnsh('./Kernels/PJ{}_metakernel.txt'.format(pj))

    time_str = np.array([t.iso for t in data_Table['UTC']])
    spiceyTimes = spice.str2et(time_str)

    positions, lightTimes = spice.spkpos('JUNO', spiceyTimes, 'IAU_JUPITER', 'NONE', 'JUPITER_BARYCENTER')
    lon = []
    lat = []
    for spiceyTime in tqdm(spiceyTimes):
        spoint, trgepc, srfvec = spice.subpnt('NEAR POINT: ELLIPSOID', 'JUPITER', spiceyTime, 'IAU_JUPITER', 'NONE', 'JUNO')
        srad, slon, slat = spice.reclat(spoint)
        lon.append(slon * spice.dpr())
        lat.append(slat * spice.dpr())
```
data_Table['UTC'] is a list of times with a dt of 60 seconds spanning from 2017-297/16:12:31 to 2017-297/19:12:31

And the meta kernel I have been using is:

[PJ09_metakernel.txt](https://github.com/AndrewAnnex/SpiceyPy/files/5386526/PJ09_metakernel.txt)
The specific kernels referenced can be downloaded through NAIF with the urls contained In the following file

[Kernel_url.txt](https://github.com/AndrewAnnex/SpiceyPy/files/5386651/Kernel_url.txt)

**Desktop (please complete the following information):**
 - SpiceyPy Version 3.1.1
 - OS: Mac OsX 10.15.5
 - OS Architecture 64bit
 - Python Version 3.9.0
 - Python Architecture 64bit

**Comment by jessemapel** [comment]
What web based SPICE interface were you using? I'm also confused about the time ranges, it's hard to compare the graphs with different scaling and axis labels.

**Comment by gabrielb09** [comment]
The web based interface is [WebGeocalc](https://wgc.jpl.nasa.gov:8443/webgeocalc/#SubObserverPoint) its provided and maintained by NAIF. While the plots above have different aspect ratios they cover the exact same span of time (2017-297/16:12:31 to 2017-297/19:12:31) and show the same data (longitude for the two top plots and latitude for the two bottom plots).

**Comment by AndrewAnnex** [comment]
@gabrielb09 thanks for the detailed post, could you also post the exact list of the data table of utc dates (the time_str array as a csv) or how you generated (exact python commands)? I am wondering if there is some issue with how those et times are being converted. You can probably quickly check the spiceytimes array to ensure it is monotonic as well, if they are not then the data artifact is caused by querying for the spacecraft state at a unexpected time

**Comment by AndrewAnnex** [comment]
@gabrielb09 I confirmed that this looks like a issue with how you are converting your utc times into et times, I made the following notebook with your code and with a different procedure to produce the times and got the same plots as you made with webgeocalc
[spiceypy_debug_juno.pdf](https://github.com/AndrewAnnex/SpiceyPy/files/5387005/spiceypy_debug_juno.pdf)

**Comment by gabrielb09** [comment]
Thank you so much for your help, after further investigation you were right! My time array had some missing values, that will teach me to blindly trust my data!
