### ISSUE TITLE
Installation on MacOS

### ISSUE THREAD

**Issue by Spo-ck** [AndrewAnnex/SpiceyPy#406]
**Describe the bug**
I recently had a problem with installing spiceypy on my Mac. According to the Error Message, a problem with downloading cspice from NAIF occurred. On the NAIF site, I noticed that the name of the cspice archives for MacOS had the file ending "tar.Z" instead of "tar.gz" (which is also used for the cspice archives for other OS). 
After downloading the spiceypy and cspice archives, installing spiceypy in my python venv manually using the terminal worked as expected.

**To Reproduce**
Try to install spiceypi in pycharm or in a terminal using `pip3 install spiceypy`

**CSPICE Archive**
https://naif.jpl.nasa.gov/naif/toolkit_C_MacIntel_OSX_AppleC_64bit.html

**Desktop (please complete the following information):**
 - MacOS 64bit
 - Python 3.7, 64bit

**Comment by AndrewAnnex** [comment]
@Spo-ck I think you may have misinterpreted the error message, without the exact error message included in this issue I cannot diagnose this issue further. SpiceyPy downloads from the existing urls have been working for years, and CI tests run weekly verifying everything is working see https://github.com/AndrewAnnex/SpiceyPy/actions/runs/524582125 . If I had to guess, you may have had a networking issue or you need to update your certificates using `pip install  --upgrade certifi`

**Comment by AndrewAnnex** [comment]
@Spo-ck I am closing this issue for now as I don't have enough information to diagnose the issue you experienced. If you can repeat the issue and respond with the full log of the error I will re-open
