### ISSUE TITLE
get celestial body position at a given gps coordinate

### ISSUE THREAD

**Issue by gyillikci** [AndrewAnnex/SpiceyPy#434]
Hello Andrew,

Thanks for this beautiful repo. I would like to have clue to create trajectory of a given celestial body such as Moon or Sun at  a given GPS coordinate just like the star walk2 or skyview apps. But I am bogged down on the complexity of the library.  how can I utilize the SPICE to get me going?

Best,

Giray

**Comment by AndrewAnnex** [comment]
@gyillikci, unfortunately unbounded questions about how to use spice to do something, while interesting, are not something I have the time to respond to. You are more likely to get a helpful response from the NAIF or by asking on the openplanetary forum https://forum.openplanetary.org/ . I will leave this issue open for a day or two, but will close it afterwards.
