### ISSUE TITLE
v4.0.3 : "function 'bodeul_' not found" after update

### ISSUE THREAD

**Issue by bogpok** [AndrewAnnex/SpiceyPy#437]
**Describe the bug**
After I updated spiceypy to 4.0.3 it throws an error on importing the module:

Traceback (most recent call last):
  File "p_jup_sys.py", line 6, in <module>
    import spiceypy as spice
  File "D:\AnacondaPy\lib\site-packages\spiceypy\__init__.py", line 27, in <module>
    from .spiceypy import *
  File "D:\AnacondaPy\lib\site-packages\spiceypy\spiceypy.py", line 36, in <module>
    from .utils.libspicehelper import libspice
  File "D:\AnacondaPy\lib\site-packages\spiceypy\utils\libspicehelper.py", line 80, in <module>
    c_double_p,
  File "D:\AnacondaPy\lib\ctypes\__init__.py", line 377, in __getattr__
    func = self.__getitem__(name)
  File "D:\AnacondaPy\lib\ctypes\__init__.py", line 382, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: function 'bodeul_' not found

**Desktop (please complete the following information):**
 - SpiceyPy Version: 4.0.3
 - OS: Windows 10
 - OS Architecture 64bit
 - Python Version and Architecture: Python 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32

How can I manage it?

**Comment by bogpok** [comment]
I just have installed spiceypy on usual python and ran it from PowerShell:

Python 3.9.1 (tags/v3.9.1:1e5d33e, Dec  7 2020, 17:08:21) [MSC v.1927 64 bit (AMD64)] on win32

and 4.0.3 version works fine. So I guess there was a problem with installation or there is a problem with conda, I will try to reinstall whole conda package.

**Comment by bogpok** [comment]
It was installed exactly as it says [here](https://spiceypy.readthedocs.io/en/main/installation.html)
i. e. 
`conda config --add channels conda-forge`
`conda install spiceypy`

**Comment by jessemapel** [comment]
What version of cspice did you get? You can use `conda list cspice` to see.

If you have an older version of cspice, it could be missing https://github.com/conda-forge/csmapi-feedstock/pull/10#issuecomment-1030842701 as bodeul_ is one of the functions thats a part of the library, but not documented in cspice.
