### ISSUE TITLE
 [WinError 126] The specified module could not be found

### ISSUE THREAD

**Issue by gfferran** [AndrewAnnex/SpiceyPy#444]
Following @AndrewAnnex 's answer in #242 , I installed SpiceyPy through:
`pip install spiceypy --no-cache-dir --no-binary :all:`

Then, when I try to import, this error appears:
```
Traceback (most recent call last):
  File ".\test_spiceypy.py", line 2, in <module>
    import spiceypy
  File "C:\Python37\lib\site-packages\spiceypy\__init__.py", line 27, in <module>
    from .spiceypy import *
  File "C:\Python37\lib\site-packages\spiceypy\spiceypy.py", line 36, in <module>
    from .utils.libspicehelper import libspice
  File "C:\Python37\lib\site-packages\spiceypy\utils\libspicehelper.py", line 57, in <module>
    libspice = CDLL(libspice_path)
  File "C:\Python37\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
```

This is the setup:
- Windows 10
- Python 3.7.3 (32-bit)
- pip 22.0.4 from c:\python37\lib\site-packages\pip
- spiceypy==5.0.1
- glibc==0.6.1
- setuptools==61.3.1
- wheel==0.37.1

**Comment by AndrewAnnex** [comment]
hey @gfferran, I thought I replied to this over email but it looks like it never got sent. Your python is 32-bit and is unsupported by spiceypy. Since you are using windows 10, you should be able to install a 64 bit version of python from python.org, and then you can simply run `pip install spiceypy` without all the options from that old issue.

**Comment by AndrewAnnex** [comment]
closing this issue for lack of updates

**Comment by gfferran** [comment]
Thank you for your reply, Andrew, it worked. Sorry for the late reply.

**Comment by AndrewAnnex** [comment]
Hi Fernando,

That advice is 5 years out of date. Uninstall spiceypy, then reinstall it using just “pip install spiceypy” without those additional options 

-Andrew Annex
