### ISSUE TITLE
Toolkit version: CSPICE_N0067

### ISSUE THREAD

**Issue by yangyang-studio** [AndrewAnnex/SpiceyPy#463]
Hello, sir 
I am using python to write code, will encounter n0067 version of the error, I hope you can help see, I have to deal with this side? Thanks 

(win 10)

Good luck with your work 

SpiceNOLEAPSECONDS: 
================================================================================

Toolkit version: CSPICE_N0067

SPICE(NOLEAPSECONDS) --

The variable that points to the leapseconds (DELTET/DELTA_AT) could not be located in the kernel pool. It is likely that the leapseconds kernel has not been loaded.

str2et_c --> STR2ET --> TTRANS

================================================================================

From:ZY-LunarCrater

**Comment by AndrewAnnex** [comment]
the error message above indicates that you haven't loaded a leapseconds kernel (.lsk) using the `furnsh` function. This isn't a bug, and so you may have more to learn more about how to use spice correctly. I suggest reading more of the tutorials and documentation available at https://naif.jpl.nasa.gov/.
